namespace BloodBankManagement
{
    partial class FrmAdmin
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmAdmin));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges33 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges34 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges35 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges36 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.pnlDashboard = new Bunifu.UI.WinForms.BunifuPanel();
            this.btDonations = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btLogOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btRequirements = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btBloodStock = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btReUnits = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btDonors = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btEvents = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pnlHome = new Bunifu.UI.WinForms.BunifuPanel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.pnlUserControl = new Bunifu.UI.WinForms.BunifuPanel();
            this.pnlDashboard.SuspendLayout();
            this.pnlHome.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // pnlDashboard
            // 
            this.pnlDashboard.BackgroundColor = System.Drawing.Color.White;
            this.pnlDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlDashboard.BackgroundImage")));
            this.pnlDashboard.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlDashboard.BorderColor = System.Drawing.Color.Transparent;
            this.pnlDashboard.BorderRadius = 3;
            this.pnlDashboard.BorderThickness = 1;
            this.pnlDashboard.Controls.Add(this.btDonations);
            this.pnlDashboard.Controls.Add(this.btLogOut);
            this.pnlDashboard.Controls.Add(this.btHome);
            this.pnlDashboard.Controls.Add(this.btRequirements);
            this.pnlDashboard.Controls.Add(this.btDashboard);
            this.pnlDashboard.Controls.Add(this.btBloodStock);
            this.pnlDashboard.Controls.Add(this.btReUnits);
            this.pnlDashboard.Controls.Add(this.btDonors);
            this.pnlDashboard.Controls.Add(this.btEvents);
            this.pnlDashboard.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlDashboard.Location = new System.Drawing.Point(0, 134);
            this.pnlDashboard.Margin = new System.Windows.Forms.Padding(4);
            this.pnlDashboard.Name = "pnlDashboard";
            this.pnlDashboard.ShowBorders = true;
            this.pnlDashboard.Size = new System.Drawing.Size(432, 1364);
            this.pnlDashboard.TabIndex = 4;
            // 
            // btDonations
            // 
            this.btDonations.AllowAnimations = true;
            this.btDonations.AllowMouseEffects = true;
            this.btDonations.AllowToggling = false;
            this.btDonations.AnimationSpeed = 200;
            this.btDonations.AutoGenerateColors = false;
            this.btDonations.AutoRoundBorders = false;
            this.btDonations.AutoSizeLeftIcon = true;
            this.btDonations.AutoSizeRightIcon = true;
            this.btDonations.BackColor = System.Drawing.Color.Transparent;
            this.btDonations.BackColor1 = System.Drawing.Color.White;
            this.btDonations.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btDonations.BackgroundImage")));
            this.btDonations.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonations.ButtonText = "Donations";
            this.btDonations.ButtonTextMarginLeft = 0;
            this.btDonations.ColorContrastOnClick = 45;
            this.btDonations.ColorContrastOnHover = 45;
            this.btDonations.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges28.BottomLeft = true;
            borderEdges28.BottomRight = true;
            borderEdges28.TopLeft = true;
            borderEdges28.TopRight = true;
            this.btDonations.CustomizableEdges = borderEdges28;
            this.btDonations.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btDonations.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDonations.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btDonations.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btDonations.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btDonations.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btDonations.ForeColor = System.Drawing.Color.Gray;
            this.btDonations.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDonations.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btDonations.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btDonations.IconMarginLeft = 11;
            this.btDonations.IconPadding = 10;
            this.btDonations.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDonations.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btDonations.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btDonations.IconSize = 25;
            this.btDonations.IdleBorderColor = System.Drawing.Color.White;
            this.btDonations.IdleBorderRadius = 1;
            this.btDonations.IdleBorderThickness = 1;
            this.btDonations.IdleFillColor = System.Drawing.Color.White;
            this.btDonations.IdleIconLeftImage = null;
            this.btDonations.IdleIconRightImage = null;
            this.btDonations.IndicateFocus = false;
            this.btDonations.Location = new System.Drawing.Point(0, 450);
            this.btDonations.Margin = new System.Windows.Forms.Padding(4);
            this.btDonations.Name = "btDonations";
            this.btDonations.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDonations.OnDisabledState.BorderRadius = 1;
            this.btDonations.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonations.OnDisabledState.BorderThickness = 1;
            this.btDonations.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btDonations.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btDonations.OnDisabledState.IconLeftImage = null;
            this.btDonations.OnDisabledState.IconRightImage = null;
            this.btDonations.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btDonations.onHoverState.BorderRadius = 1;
            this.btDonations.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonations.onHoverState.BorderThickness = 1;
            this.btDonations.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btDonations.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btDonations.onHoverState.IconLeftImage = null;
            this.btDonations.onHoverState.IconRightImage = null;
            this.btDonations.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btDonations.OnIdleState.BorderRadius = 1;
            this.btDonations.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonations.OnIdleState.BorderThickness = 1;
            this.btDonations.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btDonations.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btDonations.OnIdleState.IconLeftImage = null;
            this.btDonations.OnIdleState.IconRightImage = null;
            this.btDonations.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btDonations.OnPressedState.BorderRadius = 1;
            this.btDonations.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonations.OnPressedState.BorderThickness = 1;
            this.btDonations.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btDonations.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btDonations.OnPressedState.IconLeftImage = null;
            this.btDonations.OnPressedState.IconRightImage = null;
            this.btDonations.Size = new System.Drawing.Size(428, 80);
            this.btDonations.TabIndex = 1;
            this.btDonations.TabStop = false;
            this.btDonations.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDonations.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btDonations.TextMarginLeft = 0;
            this.btDonations.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btDonations.UseDefaultRadiusAndThickness = true;
            // 
            // btLogOut
            // 
            this.btLogOut.AllowAnimations = true;
            this.btLogOut.AllowMouseEffects = true;
            this.btLogOut.AllowToggling = false;
            this.btLogOut.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btLogOut.AnimationSpeed = 200;
            this.btLogOut.AutoGenerateColors = false;
            this.btLogOut.AutoRoundBorders = false;
            this.btLogOut.AutoSizeLeftIcon = true;
            this.btLogOut.AutoSizeRightIcon = true;
            this.btLogOut.BackColor = System.Drawing.Color.Transparent;
            this.btLogOut.BackColor1 = System.Drawing.Color.White;
            this.btLogOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btLogOut.BackgroundImage")));
            this.btLogOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogOut.ButtonText = "Log Out";
            this.btLogOut.ButtonTextMarginLeft = 0;
            this.btLogOut.ColorContrastOnClick = 45;
            this.btLogOut.ColorContrastOnHover = 45;
            this.btLogOut.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges29.BottomLeft = true;
            borderEdges29.BottomRight = true;
            borderEdges29.TopLeft = true;
            borderEdges29.TopRight = true;
            this.btLogOut.CustomizableEdges = borderEdges29;
            this.btLogOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btLogOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btLogOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btLogOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btLogOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btLogOut.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btLogOut.ForeColor = System.Drawing.Color.Gray;
            this.btLogOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btLogOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btLogOut.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btLogOut.IconMarginLeft = 11;
            this.btLogOut.IconPadding = 10;
            this.btLogOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btLogOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btLogOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btLogOut.IconSize = 25;
            this.btLogOut.IdleBorderColor = System.Drawing.Color.White;
            this.btLogOut.IdleBorderRadius = 1;
            this.btLogOut.IdleBorderThickness = 1;
            this.btLogOut.IdleFillColor = System.Drawing.Color.White;
            this.btLogOut.IdleIconLeftImage = null;
            this.btLogOut.IdleIconRightImage = null;
            this.btLogOut.IndicateFocus = false;
            this.btLogOut.Location = new System.Drawing.Point(0, 1216);
            this.btLogOut.Margin = new System.Windows.Forms.Padding(4);
            this.btLogOut.Name = "btLogOut";
            this.btLogOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btLogOut.OnDisabledState.BorderRadius = 1;
            this.btLogOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogOut.OnDisabledState.BorderThickness = 1;
            this.btLogOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btLogOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btLogOut.OnDisabledState.IconLeftImage = null;
            this.btLogOut.OnDisabledState.IconRightImage = null;
            this.btLogOut.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btLogOut.onHoverState.BorderRadius = 1;
            this.btLogOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogOut.onHoverState.BorderThickness = 1;
            this.btLogOut.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btLogOut.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btLogOut.onHoverState.IconLeftImage = null;
            this.btLogOut.onHoverState.IconRightImage = null;
            this.btLogOut.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btLogOut.OnIdleState.BorderRadius = 1;
            this.btLogOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogOut.OnIdleState.BorderThickness = 1;
            this.btLogOut.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btLogOut.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btLogOut.OnIdleState.IconLeftImage = null;
            this.btLogOut.OnIdleState.IconRightImage = null;
            this.btLogOut.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btLogOut.OnPressedState.BorderRadius = 1;
            this.btLogOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogOut.OnPressedState.BorderThickness = 1;
            this.btLogOut.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btLogOut.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btLogOut.OnPressedState.IconLeftImage = null;
            this.btLogOut.OnPressedState.IconRightImage = null;
            this.btLogOut.Size = new System.Drawing.Size(384, 66);
            this.btLogOut.TabIndex = 0;
            this.btLogOut.TabStop = false;
            this.btLogOut.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btLogOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btLogOut.TextMarginLeft = 0;
            this.btLogOut.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btLogOut.UseDefaultRadiusAndThickness = true;
            this.btLogOut.Click += new System.EventHandler(this.btLogOut_Click);
            // 
            // btHome
            // 
            this.btHome.AllowAnimations = true;
            this.btHome.AllowMouseEffects = true;
            this.btHome.AllowToggling = false;
            this.btHome.AnimationSpeed = 200;
            this.btHome.AutoGenerateColors = false;
            this.btHome.AutoRoundBorders = false;
            this.btHome.AutoSizeLeftIcon = true;
            this.btHome.AutoSizeRightIcon = true;
            this.btHome.BackColor = System.Drawing.Color.Transparent;
            this.btHome.BackColor1 = System.Drawing.Color.White;
            this.btHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btHome.BackgroundImage")));
            this.btHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.ButtonText = "Home";
            this.btHome.ButtonTextMarginLeft = 0;
            this.btHome.ColorContrastOnClick = 45;
            this.btHome.ColorContrastOnHover = 45;
            this.btHome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges30.BottomLeft = true;
            borderEdges30.BottomRight = true;
            borderEdges30.TopLeft = true;
            borderEdges30.TopRight = true;
            this.btHome.CustomizableEdges = borderEdges30;
            this.btHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btHome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btHome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btHome.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btHome.ForeColor = System.Drawing.Color.Gray;
            this.btHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btHome.IconMarginLeft = 11;
            this.btHome.IconPadding = 10;
            this.btHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btHome.IconSize = 25;
            this.btHome.IdleBorderColor = System.Drawing.Color.White;
            this.btHome.IdleBorderRadius = 1;
            this.btHome.IdleBorderThickness = 1;
            this.btHome.IdleFillColor = System.Drawing.Color.White;
            this.btHome.IdleIconLeftImage = null;
            this.btHome.IdleIconRightImage = null;
            this.btHome.IndicateFocus = false;
            this.btHome.Location = new System.Drawing.Point(0, 156);
            this.btHome.Margin = new System.Windows.Forms.Padding(4);
            this.btHome.Name = "btHome";
            this.btHome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btHome.OnDisabledState.BorderRadius = 1;
            this.btHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.OnDisabledState.BorderThickness = 1;
            this.btHome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btHome.OnDisabledState.IconLeftImage = null;
            this.btHome.OnDisabledState.IconRightImage = null;
            this.btHome.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btHome.onHoverState.BorderRadius = 1;
            this.btHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.onHoverState.BorderThickness = 1;
            this.btHome.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btHome.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btHome.onHoverState.IconLeftImage = null;
            this.btHome.onHoverState.IconRightImage = null;
            this.btHome.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btHome.OnIdleState.BorderRadius = 1;
            this.btHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.OnIdleState.BorderThickness = 1;
            this.btHome.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btHome.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btHome.OnIdleState.IconLeftImage = null;
            this.btHome.OnIdleState.IconRightImage = null;
            this.btHome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btHome.OnPressedState.BorderRadius = 1;
            this.btHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.OnPressedState.BorderThickness = 1;
            this.btHome.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btHome.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btHome.OnPressedState.IconLeftImage = null;
            this.btHome.OnPressedState.IconRightImage = null;
            this.btHome.Size = new System.Drawing.Size(428, 80);
            this.btHome.TabIndex = 0;
            this.btHome.TabStop = false;
            this.btHome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btHome.TextMarginLeft = 0;
            this.btHome.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btHome.UseDefaultRadiusAndThickness = true;
            this.btHome.Click += new System.EventHandler(this.btHome_Click);
            // 
            // btRequirements
            // 
            this.btRequirements.AllowAnimations = true;
            this.btRequirements.AllowMouseEffects = true;
            this.btRequirements.AllowToggling = false;
            this.btRequirements.AnimationSpeed = 200;
            this.btRequirements.AutoGenerateColors = false;
            this.btRequirements.AutoRoundBorders = false;
            this.btRequirements.AutoSizeLeftIcon = true;
            this.btRequirements.AutoSizeRightIcon = true;
            this.btRequirements.BackColor = System.Drawing.Color.Transparent;
            this.btRequirements.BackColor1 = System.Drawing.Color.White;
            this.btRequirements.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btRequirements.BackgroundImage")));
            this.btRequirements.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRequirements.ButtonText = "Requirements";
            this.btRequirements.ButtonTextMarginLeft = 0;
            this.btRequirements.ColorContrastOnClick = 45;
            this.btRequirements.ColorContrastOnHover = 45;
            this.btRequirements.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges31.BottomLeft = true;
            borderEdges31.BottomRight = true;
            borderEdges31.TopLeft = true;
            borderEdges31.TopRight = true;
            this.btRequirements.CustomizableEdges = borderEdges31;
            this.btRequirements.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btRequirements.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btRequirements.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btRequirements.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btRequirements.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btRequirements.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btRequirements.ForeColor = System.Drawing.Color.Gray;
            this.btRequirements.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btRequirements.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btRequirements.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btRequirements.IconMarginLeft = 11;
            this.btRequirements.IconPadding = 10;
            this.btRequirements.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btRequirements.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btRequirements.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btRequirements.IconSize = 25;
            this.btRequirements.IdleBorderColor = System.Drawing.Color.White;
            this.btRequirements.IdleBorderRadius = 1;
            this.btRequirements.IdleBorderThickness = 1;
            this.btRequirements.IdleFillColor = System.Drawing.Color.White;
            this.btRequirements.IdleIconLeftImage = null;
            this.btRequirements.IdleIconRightImage = null;
            this.btRequirements.IndicateFocus = false;
            this.btRequirements.Location = new System.Drawing.Point(0, 646);
            this.btRequirements.Margin = new System.Windows.Forms.Padding(4);
            this.btRequirements.Name = "btRequirements";
            this.btRequirements.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btRequirements.OnDisabledState.BorderRadius = 1;
            this.btRequirements.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRequirements.OnDisabledState.BorderThickness = 1;
            this.btRequirements.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btRequirements.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btRequirements.OnDisabledState.IconLeftImage = null;
            this.btRequirements.OnDisabledState.IconRightImage = null;
            this.btRequirements.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btRequirements.onHoverState.BorderRadius = 1;
            this.btRequirements.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRequirements.onHoverState.BorderThickness = 1;
            this.btRequirements.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btRequirements.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btRequirements.onHoverState.IconLeftImage = null;
            this.btRequirements.onHoverState.IconRightImage = null;
            this.btRequirements.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btRequirements.OnIdleState.BorderRadius = 1;
            this.btRequirements.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRequirements.OnIdleState.BorderThickness = 1;
            this.btRequirements.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btRequirements.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btRequirements.OnIdleState.IconLeftImage = null;
            this.btRequirements.OnIdleState.IconRightImage = null;
            this.btRequirements.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btRequirements.OnPressedState.BorderRadius = 1;
            this.btRequirements.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRequirements.OnPressedState.BorderThickness = 1;
            this.btRequirements.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btRequirements.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btRequirements.OnPressedState.IconLeftImage = null;
            this.btRequirements.OnPressedState.IconRightImage = null;
            this.btRequirements.Size = new System.Drawing.Size(428, 80);
            this.btRequirements.TabIndex = 0;
            this.btRequirements.TabStop = false;
            this.btRequirements.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btRequirements.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btRequirements.TextMarginLeft = 0;
            this.btRequirements.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btRequirements.UseDefaultRadiusAndThickness = true;
            this.btRequirements.Click += new System.EventHandler(this.btRequirements_Click);
            // 
            // btDashboard
            // 
            this.btDashboard.AllowAnimations = true;
            this.btDashboard.AllowMouseEffects = true;
            this.btDashboard.AllowToggling = false;
            this.btDashboard.AnimationSpeed = 200;
            this.btDashboard.AutoGenerateColors = false;
            this.btDashboard.AutoRoundBorders = false;
            this.btDashboard.AutoSizeLeftIcon = true;
            this.btDashboard.AutoSizeRightIcon = true;
            this.btDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btDashboard.BackColor1 = System.Drawing.Color.White;
            this.btDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btDashboard.BackgroundImage")));
            this.btDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDashboard.ButtonText = "Dashboard";
            this.btDashboard.ButtonTextMarginLeft = 0;
            this.btDashboard.ColorContrastOnClick = 45;
            this.btDashboard.ColorContrastOnHover = 45;
            this.btDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges32.BottomLeft = true;
            borderEdges32.BottomRight = true;
            borderEdges32.TopLeft = true;
            borderEdges32.TopRight = true;
            this.btDashboard.CustomizableEdges = borderEdges32;
            this.btDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btDashboard.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btDashboard.ForeColor = System.Drawing.Color.Gray;
            this.btDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btDashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btDashboard.IconMarginLeft = 11;
            this.btDashboard.IconPadding = 10;
            this.btDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btDashboard.IconSize = 25;
            this.btDashboard.IdleBorderColor = System.Drawing.Color.White;
            this.btDashboard.IdleBorderRadius = 1;
            this.btDashboard.IdleBorderThickness = 1;
            this.btDashboard.IdleFillColor = System.Drawing.Color.White;
            this.btDashboard.IdleIconLeftImage = null;
            this.btDashboard.IdleIconRightImage = null;
            this.btDashboard.IndicateFocus = false;
            this.btDashboard.Location = new System.Drawing.Point(0, 842);
            this.btDashboard.Margin = new System.Windows.Forms.Padding(4);
            this.btDashboard.Name = "btDashboard";
            this.btDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDashboard.OnDisabledState.BorderRadius = 1;
            this.btDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDashboard.OnDisabledState.BorderThickness = 1;
            this.btDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btDashboard.OnDisabledState.IconLeftImage = null;
            this.btDashboard.OnDisabledState.IconRightImage = null;
            this.btDashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btDashboard.onHoverState.BorderRadius = 1;
            this.btDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDashboard.onHoverState.BorderThickness = 1;
            this.btDashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btDashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btDashboard.onHoverState.IconLeftImage = null;
            this.btDashboard.onHoverState.IconRightImage = null;
            this.btDashboard.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btDashboard.OnIdleState.BorderRadius = 1;
            this.btDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDashboard.OnIdleState.BorderThickness = 1;
            this.btDashboard.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btDashboard.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btDashboard.OnIdleState.IconLeftImage = null;
            this.btDashboard.OnIdleState.IconRightImage = null;
            this.btDashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btDashboard.OnPressedState.BorderRadius = 1;
            this.btDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDashboard.OnPressedState.BorderThickness = 1;
            this.btDashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btDashboard.OnPressedState.IconLeftImage = null;
            this.btDashboard.OnPressedState.IconRightImage = null;
            this.btDashboard.Size = new System.Drawing.Size(428, 80);
            this.btDashboard.TabIndex = 0;
            this.btDashboard.TabStop = false;
            this.btDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btDashboard.TextMarginLeft = 0;
            this.btDashboard.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btDashboard.UseDefaultRadiusAndThickness = true;
            // 
            // btBloodStock
            // 
            this.btBloodStock.AllowAnimations = true;
            this.btBloodStock.AllowMouseEffects = true;
            this.btBloodStock.AllowToggling = false;
            this.btBloodStock.AnimationSpeed = 200;
            this.btBloodStock.AutoGenerateColors = false;
            this.btBloodStock.AutoRoundBorders = false;
            this.btBloodStock.AutoSizeLeftIcon = true;
            this.btBloodStock.AutoSizeRightIcon = true;
            this.btBloodStock.BackColor = System.Drawing.Color.Transparent;
            this.btBloodStock.BackColor1 = System.Drawing.Color.White;
            this.btBloodStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btBloodStock.BackgroundImage")));
            this.btBloodStock.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBloodStock.ButtonText = "Blood Stock";
            this.btBloodStock.ButtonTextMarginLeft = 0;
            this.btBloodStock.ColorContrastOnClick = 45;
            this.btBloodStock.ColorContrastOnHover = 45;
            this.btBloodStock.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges33.BottomLeft = true;
            borderEdges33.BottomRight = true;
            borderEdges33.TopLeft = true;
            borderEdges33.TopRight = true;
            this.btBloodStock.CustomizableEdges = borderEdges33;
            this.btBloodStock.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btBloodStock.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btBloodStock.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btBloodStock.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btBloodStock.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btBloodStock.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btBloodStock.ForeColor = System.Drawing.Color.Gray;
            this.btBloodStock.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btBloodStock.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btBloodStock.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btBloodStock.IconMarginLeft = 11;
            this.btBloodStock.IconPadding = 10;
            this.btBloodStock.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btBloodStock.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btBloodStock.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btBloodStock.IconSize = 25;
            this.btBloodStock.IdleBorderColor = System.Drawing.Color.White;
            this.btBloodStock.IdleBorderRadius = 1;
            this.btBloodStock.IdleBorderThickness = 1;
            this.btBloodStock.IdleFillColor = System.Drawing.Color.White;
            this.btBloodStock.IdleIconLeftImage = null;
            this.btBloodStock.IdleIconRightImage = null;
            this.btBloodStock.IndicateFocus = false;
            this.btBloodStock.Location = new System.Drawing.Point(0, 744);
            this.btBloodStock.Margin = new System.Windows.Forms.Padding(4);
            this.btBloodStock.Name = "btBloodStock";
            this.btBloodStock.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btBloodStock.OnDisabledState.BorderRadius = 1;
            this.btBloodStock.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBloodStock.OnDisabledState.BorderThickness = 1;
            this.btBloodStock.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btBloodStock.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btBloodStock.OnDisabledState.IconLeftImage = null;
            this.btBloodStock.OnDisabledState.IconRightImage = null;
            this.btBloodStock.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btBloodStock.onHoverState.BorderRadius = 1;
            this.btBloodStock.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBloodStock.onHoverState.BorderThickness = 1;
            this.btBloodStock.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btBloodStock.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btBloodStock.onHoverState.IconLeftImage = null;
            this.btBloodStock.onHoverState.IconRightImage = null;
            this.btBloodStock.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btBloodStock.OnIdleState.BorderRadius = 1;
            this.btBloodStock.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBloodStock.OnIdleState.BorderThickness = 1;
            this.btBloodStock.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btBloodStock.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btBloodStock.OnIdleState.IconLeftImage = null;
            this.btBloodStock.OnIdleState.IconRightImage = null;
            this.btBloodStock.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btBloodStock.OnPressedState.BorderRadius = 1;
            this.btBloodStock.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBloodStock.OnPressedState.BorderThickness = 1;
            this.btBloodStock.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btBloodStock.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btBloodStock.OnPressedState.IconLeftImage = null;
            this.btBloodStock.OnPressedState.IconRightImage = null;
            this.btBloodStock.Size = new System.Drawing.Size(428, 80);
            this.btBloodStock.TabIndex = 0;
            this.btBloodStock.TabStop = false;
            this.btBloodStock.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btBloodStock.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btBloodStock.TextMarginLeft = 0;
            this.btBloodStock.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btBloodStock.UseDefaultRadiusAndThickness = true;
            // 
            // btReUnits
            // 
            this.btReUnits.AllowAnimations = true;
            this.btReUnits.AllowMouseEffects = true;
            this.btReUnits.AllowToggling = false;
            this.btReUnits.AnimationSpeed = 200;
            this.btReUnits.AutoGenerateColors = false;
            this.btReUnits.AutoRoundBorders = false;
            this.btReUnits.AutoSizeLeftIcon = true;
            this.btReUnits.AutoSizeRightIcon = true;
            this.btReUnits.BackColor = System.Drawing.Color.Transparent;
            this.btReUnits.BackColor1 = System.Drawing.Color.White;
            this.btReUnits.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btReUnits.BackgroundImage")));
            this.btReUnits.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btReUnits.ButtonText = "Receiving Units";
            this.btReUnits.ButtonTextMarginLeft = 0;
            this.btReUnits.ColorContrastOnClick = 45;
            this.btReUnits.ColorContrastOnHover = 45;
            this.btReUnits.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges34.BottomLeft = true;
            borderEdges34.BottomRight = true;
            borderEdges34.TopLeft = true;
            borderEdges34.TopRight = true;
            this.btReUnits.CustomizableEdges = borderEdges34;
            this.btReUnits.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btReUnits.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btReUnits.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btReUnits.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btReUnits.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btReUnits.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btReUnits.ForeColor = System.Drawing.Color.Gray;
            this.btReUnits.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btReUnits.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btReUnits.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btReUnits.IconMarginLeft = 11;
            this.btReUnits.IconPadding = 10;
            this.btReUnits.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btReUnits.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btReUnits.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btReUnits.IconSize = 25;
            this.btReUnits.IdleBorderColor = System.Drawing.Color.White;
            this.btReUnits.IdleBorderRadius = 1;
            this.btReUnits.IdleBorderThickness = 1;
            this.btReUnits.IdleFillColor = System.Drawing.Color.White;
            this.btReUnits.IdleIconLeftImage = null;
            this.btReUnits.IdleIconRightImage = null;
            this.btReUnits.IndicateFocus = false;
            this.btReUnits.Location = new System.Drawing.Point(0, 548);
            this.btReUnits.Margin = new System.Windows.Forms.Padding(4);
            this.btReUnits.Name = "btReUnits";
            this.btReUnits.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btReUnits.OnDisabledState.BorderRadius = 1;
            this.btReUnits.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btReUnits.OnDisabledState.BorderThickness = 1;
            this.btReUnits.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btReUnits.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btReUnits.OnDisabledState.IconLeftImage = null;
            this.btReUnits.OnDisabledState.IconRightImage = null;
            this.btReUnits.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btReUnits.onHoverState.BorderRadius = 1;
            this.btReUnits.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btReUnits.onHoverState.BorderThickness = 1;
            this.btReUnits.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btReUnits.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btReUnits.onHoverState.IconLeftImage = null;
            this.btReUnits.onHoverState.IconRightImage = null;
            this.btReUnits.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btReUnits.OnIdleState.BorderRadius = 1;
            this.btReUnits.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btReUnits.OnIdleState.BorderThickness = 1;
            this.btReUnits.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btReUnits.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btReUnits.OnIdleState.IconLeftImage = null;
            this.btReUnits.OnIdleState.IconRightImage = null;
            this.btReUnits.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btReUnits.OnPressedState.BorderRadius = 1;
            this.btReUnits.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btReUnits.OnPressedState.BorderThickness = 1;
            this.btReUnits.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btReUnits.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btReUnits.OnPressedState.IconLeftImage = null;
            this.btReUnits.OnPressedState.IconRightImage = null;
            this.btReUnits.Size = new System.Drawing.Size(428, 80);
            this.btReUnits.TabIndex = 0;
            this.btReUnits.TabStop = false;
            this.btReUnits.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btReUnits.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btReUnits.TextMarginLeft = 0;
            this.btReUnits.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btReUnits.UseDefaultRadiusAndThickness = true;
            this.btReUnits.Click += new System.EventHandler(this.btReUnits_Click);
            // 
            // btDonors
            // 
            this.btDonors.AllowAnimations = true;
            this.btDonors.AllowMouseEffects = true;
            this.btDonors.AllowToggling = false;
            this.btDonors.AnimationSpeed = 200;
            this.btDonors.AutoGenerateColors = false;
            this.btDonors.AutoRoundBorders = false;
            this.btDonors.AutoSizeLeftIcon = true;
            this.btDonors.AutoSizeRightIcon = true;
            this.btDonors.BackColor = System.Drawing.Color.Transparent;
            this.btDonors.BackColor1 = System.Drawing.Color.White;
            this.btDonors.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btDonors.BackgroundImage")));
            this.btDonors.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonors.ButtonText = "Donors";
            this.btDonors.ButtonTextMarginLeft = 0;
            this.btDonors.ColorContrastOnClick = 45;
            this.btDonors.ColorContrastOnHover = 45;
            this.btDonors.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges35.BottomLeft = true;
            borderEdges35.BottomRight = true;
            borderEdges35.TopLeft = true;
            borderEdges35.TopRight = true;
            this.btDonors.CustomizableEdges = borderEdges35;
            this.btDonors.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btDonors.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDonors.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btDonors.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btDonors.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btDonors.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btDonors.ForeColor = System.Drawing.Color.Gray;
            this.btDonors.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDonors.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btDonors.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btDonors.IconMarginLeft = 11;
            this.btDonors.IconPadding = 10;
            this.btDonors.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDonors.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btDonors.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btDonors.IconSize = 25;
            this.btDonors.IdleBorderColor = System.Drawing.Color.White;
            this.btDonors.IdleBorderRadius = 1;
            this.btDonors.IdleBorderThickness = 1;
            this.btDonors.IdleFillColor = System.Drawing.Color.White;
            this.btDonors.IdleIconLeftImage = null;
            this.btDonors.IdleIconRightImage = null;
            this.btDonors.IndicateFocus = false;
            this.btDonors.Location = new System.Drawing.Point(0, 352);
            this.btDonors.Margin = new System.Windows.Forms.Padding(4);
            this.btDonors.Name = "btDonors";
            this.btDonors.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDonors.OnDisabledState.BorderRadius = 1;
            this.btDonors.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonors.OnDisabledState.BorderThickness = 1;
            this.btDonors.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btDonors.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btDonors.OnDisabledState.IconLeftImage = null;
            this.btDonors.OnDisabledState.IconRightImage = null;
            this.btDonors.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btDonors.onHoverState.BorderRadius = 1;
            this.btDonors.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonors.onHoverState.BorderThickness = 1;
            this.btDonors.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btDonors.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btDonors.onHoverState.IconLeftImage = null;
            this.btDonors.onHoverState.IconRightImage = null;
            this.btDonors.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btDonors.OnIdleState.BorderRadius = 1;
            this.btDonors.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonors.OnIdleState.BorderThickness = 1;
            this.btDonors.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btDonors.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btDonors.OnIdleState.IconLeftImage = null;
            this.btDonors.OnIdleState.IconRightImage = null;
            this.btDonors.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btDonors.OnPressedState.BorderRadius = 1;
            this.btDonors.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btDonors.OnPressedState.BorderThickness = 1;
            this.btDonors.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btDonors.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btDonors.OnPressedState.IconLeftImage = null;
            this.btDonors.OnPressedState.IconRightImage = null;
            this.btDonors.Size = new System.Drawing.Size(428, 80);
            this.btDonors.TabIndex = 0;
            this.btDonors.TabStop = false;
            this.btDonors.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDonors.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btDonors.TextMarginLeft = 0;
            this.btDonors.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btDonors.UseDefaultRadiusAndThickness = true;
            // 
            // btEvents
            // 
            this.btEvents.AllowAnimations = true;
            this.btEvents.AllowMouseEffects = true;
            this.btEvents.AllowToggling = false;
            this.btEvents.AnimationSpeed = 200;
            this.btEvents.AutoGenerateColors = false;
            this.btEvents.AutoRoundBorders = false;
            this.btEvents.AutoSizeLeftIcon = true;
            this.btEvents.AutoSizeRightIcon = true;
            this.btEvents.BackColor = System.Drawing.Color.Transparent;
            this.btEvents.BackColor1 = System.Drawing.Color.White;
            this.btEvents.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btEvents.BackgroundImage")));
            this.btEvents.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btEvents.ButtonText = "Events";
            this.btEvents.ButtonTextMarginLeft = 0;
            this.btEvents.ColorContrastOnClick = 45;
            this.btEvents.ColorContrastOnHover = 45;
            this.btEvents.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges36.BottomLeft = true;
            borderEdges36.BottomRight = true;
            borderEdges36.TopLeft = true;
            borderEdges36.TopRight = true;
            this.btEvents.CustomizableEdges = borderEdges36;
            this.btEvents.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btEvents.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btEvents.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btEvents.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btEvents.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btEvents.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btEvents.ForeColor = System.Drawing.Color.Gray;
            this.btEvents.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btEvents.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btEvents.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btEvents.IconMarginLeft = 11;
            this.btEvents.IconPadding = 10;
            this.btEvents.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btEvents.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btEvents.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btEvents.IconSize = 25;
            this.btEvents.IdleBorderColor = System.Drawing.Color.White;
            this.btEvents.IdleBorderRadius = 1;
            this.btEvents.IdleBorderThickness = 1;
            this.btEvents.IdleFillColor = System.Drawing.Color.White;
            this.btEvents.IdleIconLeftImage = null;
            this.btEvents.IdleIconRightImage = null;
            this.btEvents.IndicateFocus = false;
            this.btEvents.Location = new System.Drawing.Point(0, 254);
            this.btEvents.Margin = new System.Windows.Forms.Padding(4);
            this.btEvents.Name = "btEvents";
            this.btEvents.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btEvents.OnDisabledState.BorderRadius = 1;
            this.btEvents.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btEvents.OnDisabledState.BorderThickness = 1;
            this.btEvents.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btEvents.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btEvents.OnDisabledState.IconLeftImage = null;
            this.btEvents.OnDisabledState.IconRightImage = null;
            this.btEvents.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btEvents.onHoverState.BorderRadius = 1;
            this.btEvents.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btEvents.onHoverState.BorderThickness = 1;
            this.btEvents.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btEvents.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btEvents.onHoverState.IconLeftImage = null;
            this.btEvents.onHoverState.IconRightImage = null;
            this.btEvents.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btEvents.OnIdleState.BorderRadius = 1;
            this.btEvents.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btEvents.OnIdleState.BorderThickness = 1;
            this.btEvents.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btEvents.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btEvents.OnIdleState.IconLeftImage = null;
            this.btEvents.OnIdleState.IconRightImage = null;
            this.btEvents.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btEvents.OnPressedState.BorderRadius = 1;
            this.btEvents.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btEvents.OnPressedState.BorderThickness = 1;
            this.btEvents.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btEvents.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btEvents.OnPressedState.IconLeftImage = null;
            this.btEvents.OnPressedState.IconRightImage = null;
            this.btEvents.Size = new System.Drawing.Size(428, 80);
            this.btEvents.TabIndex = 0;
            this.btEvents.TabStop = false;
            this.btEvents.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btEvents.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btEvents.TextMarginLeft = 0;
            this.btEvents.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btEvents.UseDefaultRadiusAndThickness = true;
            // 
            // pnlHome
            // 
            this.pnlHome.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(5)))), ((int)(((byte)(5)))));
            this.pnlHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlHome.BackgroundImage")));
            this.pnlHome.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlHome.BorderColor = System.Drawing.Color.Transparent;
            this.pnlHome.BorderRadius = 3;
            this.pnlHome.BorderThickness = 1;
            this.pnlHome.Controls.Add(this.panel1);
            this.pnlHome.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHome.Location = new System.Drawing.Point(0, 0);
            this.pnlHome.Margin = new System.Windows.Forms.Padding(4);
            this.pnlHome.Name = "pnlHome";
            this.pnlHome.ShowBorders = true;
            this.pnlHome.Size = new System.Drawing.Size(2740, 134);
            this.pnlHome.TabIndex = 2;
            // 
            // panel1
            // 
            this.panel1.AutoSize = true;
            this.panel1.BackColor = System.Drawing.Color.Transparent;
            this.panel1.Controls.Add(this.bunifuLabel4);
            this.panel1.Controls.Add(this.bunifuPictureBox2);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(498, 134);
            this.panel1.TabIndex = 14;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Italic);
            this.bunifuLabel4.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.bunifuLabel4.Location = new System.Drawing.Point(140, 42);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(352, 44);
            this.bunifuLabel4.TabIndex = 3;
            this.bunifuLabel4.Text = "KVN BLOOD BANK";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = true;
            this.bunifuPictureBox2.BorderRadius = 47;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = true;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(32, 20);
            this.bunifuPictureBox2.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(94, 94);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.bunifuPictureBox2.TabIndex = 5;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // pnlUserControl
            // 
            this.pnlUserControl.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnlUserControl.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlUserControl.BackgroundImage")));
            this.pnlUserControl.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlUserControl.BorderColor = System.Drawing.Color.Transparent;
            this.pnlUserControl.BorderRadius = 3;
            this.pnlUserControl.BorderThickness = 1;
            this.pnlUserControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlUserControl.Location = new System.Drawing.Point(432, 134);
            this.pnlUserControl.Name = "pnlUserControl";
            this.pnlUserControl.ShowBorders = true;
            this.pnlUserControl.Size = new System.Drawing.Size(2308, 1364);
            this.pnlUserControl.TabIndex = 5;
            // 
            // FrmAdmin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(192F, 192F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoSize = true;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.ClientSize = new System.Drawing.Size(2740, 1498);
            this.Controls.Add(this.pnlUserControl);
            this.Controls.Add(this.pnlDashboard);
            this.Controls.Add(this.pnlHome);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "FrmAdmin";
            this.Text = "KVN BLOOD BANK";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.FrmAdmin_Load);
            this.pnlDashboard.ResumeLayout(false);
            this.pnlHome.ResumeLayout(false);
            this.pnlHome.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel pnlHome;
        private Bunifu.UI.WinForms.BunifuPanel pnlDashboard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btEvents;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btDonors;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btLogOut;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btReUnits;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btHome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btDashboard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btBloodStock;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btRequirements;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btDonations;
        private Bunifu.UI.WinForms.BunifuPanel pnlUserControl;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
    }
}

