namespace BloodBankManagement
{
    partial class FrmDonor
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmDonor));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            this.pnHome = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.pnShow = new System.Windows.Forms.Panel();
            this.pnBar = new Bunifu.UI.WinForms.BunifuPanel();
            this.btHistoryDonations = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btLogout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btBenefit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btRegisterForDonation = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btNotification = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btInfor = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pnHome.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            this.bunifuGradientPanel1.SuspendLayout();
            this.pnBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnHome
            // 
            this.pnHome.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(5)))), ((int)(((byte)(5)))));
            this.pnHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnHome.BackgroundImage")));
            this.pnHome.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnHome.BorderColor = System.Drawing.Color.Transparent;
            this.pnHome.BorderRadius = 3;
            this.pnHome.BorderThickness = 1;
            this.pnHome.Controls.Add(this.bunifuPictureBox2);
            this.pnHome.Controls.Add(this.bunifuLabel1);
            this.pnHome.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnHome.Location = new System.Drawing.Point(0, 0);
            this.pnHome.Name = "pnHome";
            this.pnHome.ShowBorders = true;
            this.pnHome.Size = new System.Drawing.Size(1924, 103);
            this.pnHome.TabIndex = 14;
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = true;
            this.bunifuPictureBox2.BorderRadius = 35;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = true;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(21, 14);
            this.bunifuPictureBox2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(70, 70);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.bunifuPictureBox2.TabIndex = 5;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Italic);
            this.bunifuLabel1.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.bunifuLabel1.Location = new System.Drawing.Point(99, 35);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(268, 33);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "KVN BLOOD BANK";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.pnShow);
            this.bunifuGradientPanel1.Controls.Add(this.pnBar);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(139)))), ((int)(((byte)(123)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(205)))), ((int)(((byte)(158)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(206)))), ((int)(((byte)(158)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(120)))), ((int)(((byte)(150)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1924, 1151);
            this.bunifuGradientPanel1.TabIndex = 16;
            // 
            // pnShow
            // 
            this.pnShow.Location = new System.Drawing.Point(330, 104);
            this.pnShow.Name = "pnShow";
            this.pnShow.Size = new System.Drawing.Size(1582, 1026);
            this.pnShow.TabIndex = 14;
            // 
            // pnBar
            // 
            this.pnBar.BackgroundColor = System.Drawing.Color.White;
            this.pnBar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnBar.BackgroundImage")));
            this.pnBar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnBar.BorderColor = System.Drawing.Color.Transparent;
            this.pnBar.BorderRadius = 3;
            this.pnBar.BorderThickness = 1;
            this.pnBar.Controls.Add(this.btHistoryDonations);
            this.pnBar.Controls.Add(this.btLogout);
            this.pnBar.Controls.Add(this.btHome);
            this.pnBar.Controls.Add(this.btBenefit);
            this.pnBar.Controls.Add(this.btRegisterForDonation);
            this.pnBar.Controls.Add(this.btNotification);
            this.pnBar.Controls.Add(this.btInfor);
            this.pnBar.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnBar.Location = new System.Drawing.Point(0, 0);
            this.pnBar.Name = "pnBar";
            this.pnBar.ShowBorders = true;
            this.pnBar.Size = new System.Drawing.Size(328, 1151);
            this.pnBar.TabIndex = 13;
            // 
            // btHistoryDonations
            // 
            this.btHistoryDonations.AllowAnimations = true;
            this.btHistoryDonations.AllowMouseEffects = true;
            this.btHistoryDonations.AllowToggling = false;
            this.btHistoryDonations.AnimationSpeed = 200;
            this.btHistoryDonations.AutoGenerateColors = false;
            this.btHistoryDonations.AutoRoundBorders = false;
            this.btHistoryDonations.AutoSizeLeftIcon = true;
            this.btHistoryDonations.AutoSizeRightIcon = true;
            this.btHistoryDonations.BackColor = System.Drawing.Color.Transparent;
            this.btHistoryDonations.BackColor1 = System.Drawing.Color.White;
            this.btHistoryDonations.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btHistoryDonations.BackgroundImage")));
            this.btHistoryDonations.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHistoryDonations.ButtonText = "History donations";
            this.btHistoryDonations.ButtonTextMarginLeft = 0;
            this.btHistoryDonations.ColorContrastOnClick = 45;
            this.btHistoryDonations.ColorContrastOnHover = 45;
            this.btHistoryDonations.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btHistoryDonations.CustomizableEdges = borderEdges1;
            this.btHistoryDonations.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btHistoryDonations.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btHistoryDonations.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btHistoryDonations.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btHistoryDonations.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btHistoryDonations.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btHistoryDonations.ForeColor = System.Drawing.Color.Gray;
            this.btHistoryDonations.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHistoryDonations.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btHistoryDonations.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btHistoryDonations.IconMarginLeft = 11;
            this.btHistoryDonations.IconPadding = 10;
            this.btHistoryDonations.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHistoryDonations.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btHistoryDonations.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btHistoryDonations.IconSize = 25;
            this.btHistoryDonations.IdleBorderColor = System.Drawing.Color.White;
            this.btHistoryDonations.IdleBorderRadius = 1;
            this.btHistoryDonations.IdleBorderThickness = 1;
            this.btHistoryDonations.IdleFillColor = System.Drawing.Color.White;
            this.btHistoryDonations.IdleIconLeftImage = null;
            this.btHistoryDonations.IdleIconRightImage = null;
            this.btHistoryDonations.IndicateFocus = false;
            this.btHistoryDonations.Location = new System.Drawing.Point(3, 255);
            this.btHistoryDonations.Name = "btHistoryDonations";
            this.btHistoryDonations.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btHistoryDonations.OnDisabledState.BorderRadius = 1;
            this.btHistoryDonations.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHistoryDonations.OnDisabledState.BorderThickness = 1;
            this.btHistoryDonations.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btHistoryDonations.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btHistoryDonations.OnDisabledState.IconLeftImage = null;
            this.btHistoryDonations.OnDisabledState.IconRightImage = null;
            this.btHistoryDonations.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btHistoryDonations.onHoverState.BorderRadius = 1;
            this.btHistoryDonations.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHistoryDonations.onHoverState.BorderThickness = 1;
            this.btHistoryDonations.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btHistoryDonations.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btHistoryDonations.onHoverState.IconLeftImage = null;
            this.btHistoryDonations.onHoverState.IconRightImage = null;
            this.btHistoryDonations.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btHistoryDonations.OnIdleState.BorderRadius = 1;
            this.btHistoryDonations.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHistoryDonations.OnIdleState.BorderThickness = 1;
            this.btHistoryDonations.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btHistoryDonations.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btHistoryDonations.OnIdleState.IconLeftImage = null;
            this.btHistoryDonations.OnIdleState.IconRightImage = null;
            this.btHistoryDonations.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btHistoryDonations.OnPressedState.BorderRadius = 1;
            this.btHistoryDonations.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHistoryDonations.OnPressedState.BorderThickness = 1;
            this.btHistoryDonations.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btHistoryDonations.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btHistoryDonations.OnPressedState.IconLeftImage = null;
            this.btHistoryDonations.OnPressedState.IconRightImage = null;
            this.btHistoryDonations.Size = new System.Drawing.Size(326, 62);
            this.btHistoryDonations.TabIndex = 1;
            this.btHistoryDonations.TabStop = false;
            this.btHistoryDonations.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHistoryDonations.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btHistoryDonations.TextMarginLeft = 0;
            this.btHistoryDonations.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btHistoryDonations.UseDefaultRadiusAndThickness = true;
            this.btHistoryDonations.Click += new System.EventHandler(this.btHistoryDonations_Click);
            // 
            // btLogout
            // 
            this.btLogout.AllowAnimations = true;
            this.btLogout.AllowMouseEffects = true;
            this.btLogout.AllowToggling = false;
            this.btLogout.AnimationSpeed = 200;
            this.btLogout.AutoGenerateColors = false;
            this.btLogout.AutoRoundBorders = false;
            this.btLogout.AutoSizeLeftIcon = true;
            this.btLogout.AutoSizeRightIcon = true;
            this.btLogout.BackColor = System.Drawing.Color.Transparent;
            this.btLogout.BackColor1 = System.Drawing.Color.White;
            this.btLogout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btLogout.BackgroundImage")));
            this.btLogout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.ButtonText = "Log Out";
            this.btLogout.ButtonTextMarginLeft = 0;
            this.btLogout.ColorContrastOnClick = 45;
            this.btLogout.ColorContrastOnHover = 45;
            this.btLogout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btLogout.CustomizableEdges = borderEdges2;
            this.btLogout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btLogout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btLogout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btLogout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btLogout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btLogout.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btLogout.ForeColor = System.Drawing.Color.Gray;
            this.btLogout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btLogout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btLogout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btLogout.IconMarginLeft = 11;
            this.btLogout.IconPadding = 10;
            this.btLogout.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btLogout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btLogout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btLogout.IconSize = 25;
            this.btLogout.IdleBorderColor = System.Drawing.Color.White;
            this.btLogout.IdleBorderRadius = 1;
            this.btLogout.IdleBorderThickness = 1;
            this.btLogout.IdleFillColor = System.Drawing.Color.White;
            this.btLogout.IdleIconLeftImage = null;
            this.btLogout.IdleIconRightImage = null;
            this.btLogout.IndicateFocus = false;
            this.btLogout.Location = new System.Drawing.Point(3, 935);
            this.btLogout.Name = "btLogout";
            this.btLogout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btLogout.OnDisabledState.BorderRadius = 1;
            this.btLogout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.OnDisabledState.BorderThickness = 1;
            this.btLogout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btLogout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btLogout.OnDisabledState.IconLeftImage = null;
            this.btLogout.OnDisabledState.IconRightImage = null;
            this.btLogout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btLogout.onHoverState.BorderRadius = 1;
            this.btLogout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.onHoverState.BorderThickness = 1;
            this.btLogout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btLogout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btLogout.onHoverState.IconLeftImage = null;
            this.btLogout.onHoverState.IconRightImage = null;
            this.btLogout.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btLogout.OnIdleState.BorderRadius = 1;
            this.btLogout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.OnIdleState.BorderThickness = 1;
            this.btLogout.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btLogout.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btLogout.OnIdleState.IconLeftImage = null;
            this.btLogout.OnIdleState.IconRightImage = null;
            this.btLogout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btLogout.OnPressedState.BorderRadius = 1;
            this.btLogout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.OnPressedState.BorderThickness = 1;
            this.btLogout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btLogout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btLogout.OnPressedState.IconLeftImage = null;
            this.btLogout.OnPressedState.IconRightImage = null;
            this.btLogout.Size = new System.Drawing.Size(326, 51);
            this.btLogout.TabIndex = 0;
            this.btLogout.TabStop = false;
            this.btLogout.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btLogout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btLogout.TextMarginLeft = 0;
            this.btLogout.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btLogout.UseDefaultRadiusAndThickness = true;
            // 
            // btHome
            // 
            this.btHome.AllowAnimations = true;
            this.btHome.AllowMouseEffects = true;
            this.btHome.AllowToggling = false;
            this.btHome.AnimationSpeed = 200;
            this.btHome.AutoGenerateColors = false;
            this.btHome.AutoRoundBorders = false;
            this.btHome.AutoSizeLeftIcon = true;
            this.btHome.AutoSizeRightIcon = true;
            this.btHome.BackColor = System.Drawing.Color.Transparent;
            this.btHome.BackColor1 = System.Drawing.Color.White;
            this.btHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btHome.BackgroundImage")));
            this.btHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.ButtonText = "Home";
            this.btHome.ButtonTextMarginLeft = 0;
            this.btHome.ColorContrastOnClick = 45;
            this.btHome.ColorContrastOnHover = 45;
            this.btHome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btHome.CustomizableEdges = borderEdges3;
            this.btHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btHome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btHome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btHome.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btHome.ForeColor = System.Drawing.Color.Gray;
            this.btHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btHome.IconMarginLeft = 11;
            this.btHome.IconPadding = 10;
            this.btHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btHome.IconSize = 25;
            this.btHome.IdleBorderColor = System.Drawing.Color.White;
            this.btHome.IdleBorderRadius = 1;
            this.btHome.IdleBorderThickness = 1;
            this.btHome.IdleFillColor = System.Drawing.Color.White;
            this.btHome.IdleIconLeftImage = null;
            this.btHome.IdleIconRightImage = null;
            this.btHome.IndicateFocus = false;
            this.btHome.Location = new System.Drawing.Point(3, 120);
            this.btHome.Name = "btHome";
            this.btHome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btHome.OnDisabledState.BorderRadius = 1;
            this.btHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.OnDisabledState.BorderThickness = 1;
            this.btHome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btHome.OnDisabledState.IconLeftImage = null;
            this.btHome.OnDisabledState.IconRightImage = null;
            this.btHome.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btHome.onHoverState.BorderRadius = 1;
            this.btHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.onHoverState.BorderThickness = 1;
            this.btHome.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btHome.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btHome.onHoverState.IconLeftImage = null;
            this.btHome.onHoverState.IconRightImage = null;
            this.btHome.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btHome.OnIdleState.BorderRadius = 1;
            this.btHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.OnIdleState.BorderThickness = 1;
            this.btHome.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btHome.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btHome.OnIdleState.IconLeftImage = null;
            this.btHome.OnIdleState.IconRightImage = null;
            this.btHome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btHome.OnPressedState.BorderRadius = 1;
            this.btHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btHome.OnPressedState.BorderThickness = 1;
            this.btHome.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btHome.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btHome.OnPressedState.IconLeftImage = null;
            this.btHome.OnPressedState.IconRightImage = null;
            this.btHome.Size = new System.Drawing.Size(326, 62);
            this.btHome.TabIndex = 0;
            this.btHome.TabStop = false;
            this.btHome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btHome.TextMarginLeft = 0;
            this.btHome.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btHome.UseDefaultRadiusAndThickness = true;
            this.btHome.Click += new System.EventHandler(this.btHome_Click);
            // 
            // btBenefit
            // 
            this.btBenefit.AllowAnimations = true;
            this.btBenefit.AllowMouseEffects = true;
            this.btBenefit.AllowToggling = false;
            this.btBenefit.AnimationSpeed = 200;
            this.btBenefit.AutoGenerateColors = false;
            this.btBenefit.AutoRoundBorders = false;
            this.btBenefit.AutoSizeLeftIcon = true;
            this.btBenefit.AutoSizeRightIcon = true;
            this.btBenefit.BackColor = System.Drawing.Color.Transparent;
            this.btBenefit.BackColor1 = System.Drawing.Color.White;
            this.btBenefit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btBenefit.BackgroundImage")));
            this.btBenefit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBenefit.ButtonText = "Benefits";
            this.btBenefit.ButtonTextMarginLeft = 0;
            this.btBenefit.ColorContrastOnClick = 45;
            this.btBenefit.ColorContrastOnHover = 45;
            this.btBenefit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btBenefit.CustomizableEdges = borderEdges4;
            this.btBenefit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btBenefit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btBenefit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btBenefit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btBenefit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btBenefit.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btBenefit.ForeColor = System.Drawing.Color.Gray;
            this.btBenefit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btBenefit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btBenefit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btBenefit.IconMarginLeft = 11;
            this.btBenefit.IconPadding = 10;
            this.btBenefit.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btBenefit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btBenefit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btBenefit.IconSize = 25;
            this.btBenefit.IdleBorderColor = System.Drawing.Color.White;
            this.btBenefit.IdleBorderRadius = 1;
            this.btBenefit.IdleBorderThickness = 1;
            this.btBenefit.IdleFillColor = System.Drawing.Color.White;
            this.btBenefit.IdleIconLeftImage = null;
            this.btBenefit.IdleIconRightImage = null;
            this.btBenefit.IndicateFocus = false;
            this.btBenefit.Location = new System.Drawing.Point(3, 463);
            this.btBenefit.Name = "btBenefit";
            this.btBenefit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btBenefit.OnDisabledState.BorderRadius = 1;
            this.btBenefit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBenefit.OnDisabledState.BorderThickness = 1;
            this.btBenefit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btBenefit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btBenefit.OnDisabledState.IconLeftImage = null;
            this.btBenefit.OnDisabledState.IconRightImage = null;
            this.btBenefit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btBenefit.onHoverState.BorderRadius = 1;
            this.btBenefit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBenefit.onHoverState.BorderThickness = 1;
            this.btBenefit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btBenefit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btBenefit.onHoverState.IconLeftImage = null;
            this.btBenefit.onHoverState.IconRightImage = null;
            this.btBenefit.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btBenefit.OnIdleState.BorderRadius = 1;
            this.btBenefit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBenefit.OnIdleState.BorderThickness = 1;
            this.btBenefit.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btBenefit.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btBenefit.OnIdleState.IconLeftImage = null;
            this.btBenefit.OnIdleState.IconRightImage = null;
            this.btBenefit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btBenefit.OnPressedState.BorderRadius = 1;
            this.btBenefit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btBenefit.OnPressedState.BorderThickness = 1;
            this.btBenefit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btBenefit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btBenefit.OnPressedState.IconLeftImage = null;
            this.btBenefit.OnPressedState.IconRightImage = null;
            this.btBenefit.Size = new System.Drawing.Size(326, 65);
            this.btBenefit.TabIndex = 0;
            this.btBenefit.TabStop = false;
            this.btBenefit.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btBenefit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btBenefit.TextMarginLeft = 0;
            this.btBenefit.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btBenefit.UseDefaultRadiusAndThickness = true;
            this.btBenefit.Click += new System.EventHandler(this.btBenefit_Click);
            // 
            // btRegisterForDonation
            // 
            this.btRegisterForDonation.AllowAnimations = true;
            this.btRegisterForDonation.AllowMouseEffects = true;
            this.btRegisterForDonation.AllowToggling = false;
            this.btRegisterForDonation.AnimationSpeed = 200;
            this.btRegisterForDonation.AutoGenerateColors = false;
            this.btRegisterForDonation.AutoRoundBorders = false;
            this.btRegisterForDonation.AutoSizeLeftIcon = true;
            this.btRegisterForDonation.AutoSizeRightIcon = true;
            this.btRegisterForDonation.BackColor = System.Drawing.Color.Transparent;
            this.btRegisterForDonation.BackColor1 = System.Drawing.Color.White;
            this.btRegisterForDonation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btRegisterForDonation.BackgroundImage")));
            this.btRegisterForDonation.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRegisterForDonation.ButtonText = "Register for Donation";
            this.btRegisterForDonation.ButtonTextMarginLeft = 0;
            this.btRegisterForDonation.ColorContrastOnClick = 45;
            this.btRegisterForDonation.ColorContrastOnHover = 45;
            this.btRegisterForDonation.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btRegisterForDonation.CustomizableEdges = borderEdges5;
            this.btRegisterForDonation.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btRegisterForDonation.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btRegisterForDonation.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btRegisterForDonation.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btRegisterForDonation.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btRegisterForDonation.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btRegisterForDonation.ForeColor = System.Drawing.Color.Gray;
            this.btRegisterForDonation.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btRegisterForDonation.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btRegisterForDonation.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btRegisterForDonation.IconMarginLeft = 11;
            this.btRegisterForDonation.IconPadding = 10;
            this.btRegisterForDonation.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btRegisterForDonation.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btRegisterForDonation.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btRegisterForDonation.IconSize = 25;
            this.btRegisterForDonation.IdleBorderColor = System.Drawing.Color.White;
            this.btRegisterForDonation.IdleBorderRadius = 1;
            this.btRegisterForDonation.IdleBorderThickness = 1;
            this.btRegisterForDonation.IdleFillColor = System.Drawing.Color.White;
            this.btRegisterForDonation.IdleIconLeftImage = null;
            this.btRegisterForDonation.IdleIconRightImage = null;
            this.btRegisterForDonation.IndicateFocus = false;
            this.btRegisterForDonation.Location = new System.Drawing.Point(2, 392);
            this.btRegisterForDonation.Name = "btRegisterForDonation";
            this.btRegisterForDonation.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btRegisterForDonation.OnDisabledState.BorderRadius = 1;
            this.btRegisterForDonation.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRegisterForDonation.OnDisabledState.BorderThickness = 1;
            this.btRegisterForDonation.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btRegisterForDonation.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btRegisterForDonation.OnDisabledState.IconLeftImage = null;
            this.btRegisterForDonation.OnDisabledState.IconRightImage = null;
            this.btRegisterForDonation.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btRegisterForDonation.onHoverState.BorderRadius = 1;
            this.btRegisterForDonation.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRegisterForDonation.onHoverState.BorderThickness = 1;
            this.btRegisterForDonation.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btRegisterForDonation.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btRegisterForDonation.onHoverState.IconLeftImage = null;
            this.btRegisterForDonation.onHoverState.IconRightImage = null;
            this.btRegisterForDonation.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btRegisterForDonation.OnIdleState.BorderRadius = 1;
            this.btRegisterForDonation.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRegisterForDonation.OnIdleState.BorderThickness = 1;
            this.btRegisterForDonation.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btRegisterForDonation.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btRegisterForDonation.OnIdleState.IconLeftImage = null;
            this.btRegisterForDonation.OnIdleState.IconRightImage = null;
            this.btRegisterForDonation.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btRegisterForDonation.OnPressedState.BorderRadius = 1;
            this.btRegisterForDonation.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btRegisterForDonation.OnPressedState.BorderThickness = 1;
            this.btRegisterForDonation.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btRegisterForDonation.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btRegisterForDonation.OnPressedState.IconLeftImage = null;
            this.btRegisterForDonation.OnPressedState.IconRightImage = null;
            this.btRegisterForDonation.Size = new System.Drawing.Size(326, 65);
            this.btRegisterForDonation.TabIndex = 0;
            this.btRegisterForDonation.TabStop = false;
            this.btRegisterForDonation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btRegisterForDonation.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btRegisterForDonation.TextMarginLeft = 0;
            this.btRegisterForDonation.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btRegisterForDonation.UseDefaultRadiusAndThickness = true;
            this.btRegisterForDonation.Click += new System.EventHandler(this.btRegisterForDonation_Click);
            // 
            // btNotification
            // 
            this.btNotification.AllowAnimations = true;
            this.btNotification.AllowMouseEffects = true;
            this.btNotification.AllowToggling = false;
            this.btNotification.AnimationSpeed = 200;
            this.btNotification.AutoGenerateColors = false;
            this.btNotification.AutoRoundBorders = false;
            this.btNotification.AutoSizeLeftIcon = true;
            this.btNotification.AutoSizeRightIcon = true;
            this.btNotification.BackColor = System.Drawing.Color.Transparent;
            this.btNotification.BackColor1 = System.Drawing.Color.White;
            this.btNotification.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btNotification.BackgroundImage")));
            this.btNotification.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btNotification.ButtonText = "Notifications";
            this.btNotification.ButtonTextMarginLeft = 0;
            this.btNotification.ColorContrastOnClick = 45;
            this.btNotification.ColorContrastOnHover = 45;
            this.btNotification.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btNotification.CustomizableEdges = borderEdges6;
            this.btNotification.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btNotification.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btNotification.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btNotification.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btNotification.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btNotification.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btNotification.ForeColor = System.Drawing.Color.Gray;
            this.btNotification.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btNotification.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btNotification.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btNotification.IconMarginLeft = 11;
            this.btNotification.IconPadding = 10;
            this.btNotification.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btNotification.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btNotification.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btNotification.IconSize = 25;
            this.btNotification.IdleBorderColor = System.Drawing.Color.White;
            this.btNotification.IdleBorderRadius = 1;
            this.btNotification.IdleBorderThickness = 1;
            this.btNotification.IdleFillColor = System.Drawing.Color.White;
            this.btNotification.IdleIconLeftImage = null;
            this.btNotification.IdleIconRightImage = null;
            this.btNotification.IndicateFocus = false;
            this.btNotification.Location = new System.Drawing.Point(3, 325);
            this.btNotification.Name = "btNotification";
            this.btNotification.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btNotification.OnDisabledState.BorderRadius = 1;
            this.btNotification.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btNotification.OnDisabledState.BorderThickness = 1;
            this.btNotification.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btNotification.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btNotification.OnDisabledState.IconLeftImage = null;
            this.btNotification.OnDisabledState.IconRightImage = null;
            this.btNotification.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btNotification.onHoverState.BorderRadius = 1;
            this.btNotification.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btNotification.onHoverState.BorderThickness = 1;
            this.btNotification.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btNotification.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btNotification.onHoverState.IconLeftImage = null;
            this.btNotification.onHoverState.IconRightImage = null;
            this.btNotification.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btNotification.OnIdleState.BorderRadius = 1;
            this.btNotification.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btNotification.OnIdleState.BorderThickness = 1;
            this.btNotification.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btNotification.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btNotification.OnIdleState.IconLeftImage = null;
            this.btNotification.OnIdleState.IconRightImage = null;
            this.btNotification.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btNotification.OnPressedState.BorderRadius = 1;
            this.btNotification.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btNotification.OnPressedState.BorderThickness = 1;
            this.btNotification.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btNotification.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btNotification.OnPressedState.IconLeftImage = null;
            this.btNotification.OnPressedState.IconRightImage = null;
            this.btNotification.Size = new System.Drawing.Size(326, 62);
            this.btNotification.TabIndex = 0;
            this.btNotification.TabStop = false;
            this.btNotification.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btNotification.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btNotification.TextMarginLeft = 0;
            this.btNotification.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btNotification.UseDefaultRadiusAndThickness = true;
            this.btNotification.Click += new System.EventHandler(this.btNotification_Click);
            // 
            // btInfor
            // 
            this.btInfor.AllowAnimations = true;
            this.btInfor.AllowMouseEffects = true;
            this.btInfor.AllowToggling = false;
            this.btInfor.AnimationSpeed = 200;
            this.btInfor.AutoGenerateColors = false;
            this.btInfor.AutoRoundBorders = false;
            this.btInfor.AutoSizeLeftIcon = true;
            this.btInfor.AutoSizeRightIcon = true;
            this.btInfor.BackColor = System.Drawing.Color.Transparent;
            this.btInfor.BackColor1 = System.Drawing.Color.White;
            this.btInfor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btInfor.BackgroundImage")));
            this.btInfor.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btInfor.ButtonText = "Personal information";
            this.btInfor.ButtonTextMarginLeft = 0;
            this.btInfor.ColorContrastOnClick = 45;
            this.btInfor.ColorContrastOnHover = 45;
            this.btInfor.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btInfor.CustomizableEdges = borderEdges7;
            this.btInfor.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btInfor.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btInfor.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btInfor.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btInfor.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btInfor.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btInfor.ForeColor = System.Drawing.Color.Gray;
            this.btInfor.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btInfor.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btInfor.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btInfor.IconMarginLeft = 11;
            this.btInfor.IconPadding = 10;
            this.btInfor.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btInfor.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btInfor.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btInfor.IconSize = 25;
            this.btInfor.IdleBorderColor = System.Drawing.Color.White;
            this.btInfor.IdleBorderRadius = 1;
            this.btInfor.IdleBorderThickness = 1;
            this.btInfor.IdleFillColor = System.Drawing.Color.White;
            this.btInfor.IdleIconLeftImage = null;
            this.btInfor.IdleIconRightImage = null;
            this.btInfor.IndicateFocus = false;
            this.btInfor.Location = new System.Drawing.Point(3, 188);
            this.btInfor.Name = "btInfor";
            this.btInfor.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btInfor.OnDisabledState.BorderRadius = 1;
            this.btInfor.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btInfor.OnDisabledState.BorderThickness = 1;
            this.btInfor.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btInfor.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btInfor.OnDisabledState.IconLeftImage = null;
            this.btInfor.OnDisabledState.IconRightImage = null;
            this.btInfor.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btInfor.onHoverState.BorderRadius = 1;
            this.btInfor.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btInfor.onHoverState.BorderThickness = 1;
            this.btInfor.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(50)))), ((int)(((byte)(234)))));
            this.btInfor.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btInfor.onHoverState.IconLeftImage = null;
            this.btInfor.onHoverState.IconRightImage = null;
            this.btInfor.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btInfor.OnIdleState.BorderRadius = 1;
            this.btInfor.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btInfor.OnIdleState.BorderThickness = 1;
            this.btInfor.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btInfor.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btInfor.OnIdleState.IconLeftImage = null;
            this.btInfor.OnIdleState.IconRightImage = null;
            this.btInfor.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btInfor.OnPressedState.BorderRadius = 1;
            this.btInfor.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btInfor.OnPressedState.BorderThickness = 1;
            this.btInfor.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btInfor.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btInfor.OnPressedState.IconLeftImage = null;
            this.btInfor.OnPressedState.IconRightImage = null;
            this.btInfor.Size = new System.Drawing.Size(326, 62);
            this.btInfor.TabIndex = 0;
            this.btInfor.TabStop = false;
            this.btInfor.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btInfor.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btInfor.TextMarginLeft = 0;
            this.btInfor.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btInfor.UseDefaultRadiusAndThickness = true;
            this.btInfor.Click += new System.EventHandler(this.btInfor_Click);
            // 
            // FrmDonor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1924, 1151);
            this.Controls.Add(this.pnHome);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Name = "FrmDonor";
            this.Text = "FrmDonor";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.FrmDonor_Load);
            this.pnHome.ResumeLayout(false);
            this.pnHome.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.pnBar.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel pnHome;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.ComponentModel.BackgroundWorker backgroundWorker1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuPanel pnBar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btHistoryDonations;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btLogout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btHome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btBenefit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btRegisterForDonation;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btNotification;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btInfor;
        private System.Windows.Forms.Panel pnShow;
    }
}