namespace BloodBankManagement
{
    partial class UC_UnitInformation
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UC_UnitInformation));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUnitName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbAvatar = new System.Windows.Forms.LinkLabel();
            this.bunifuLabel19 = new Bunifu.UI.WinForms.BunifuLabel();
            this.toggleShowPassword = new Bunifu.UI.WinForms.BunifuToggleSwitch2();
            this.txtContactName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUnitId = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPhoneNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtNewPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pbAvatar = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel15 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel16 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel17 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel18 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel14 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbUnitType = new System.Windows.Forms.ComboBox();
            this.bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.toolTipUsername = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).BeginInit();
            this.SuspendLayout();
            // 
            // txtPassword
            // 
            this.txtPassword.AcceptsReturn = false;
            this.txtPassword.AcceptsTab = false;
            this.txtPassword.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtPassword.AnimationSpeed = 200;
            this.txtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword.AutoSizeHeight = true;
            this.txtPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword.BackgroundImage")));
            this.txtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPassword.BorderRadius = 20;
            this.txtPassword.BorderThickness = 1;
            this.txtPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtPassword.DefaultText = "";
            this.txtPassword.FillColor = System.Drawing.Color.White;
            this.txtPassword.HideSelection = true;
            this.txtPassword.IconLeft = null;
            this.txtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.IconPadding = 10;
            this.txtPassword.IconRight = null;
            this.txtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.Lines = new string[0];
            this.txtPassword.Location = new System.Drawing.Point(643, 118);
            this.txtPassword.Margin = new System.Windows.Forms.Padding(6);
            this.txtPassword.MaxLength = 32767;
            this.txtPassword.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtPassword.Modified = false;
            this.txtPassword.Multiline = false;
            this.txtPassword.Name = "txtPassword";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnIdleState = stateProperties4;
            this.txtPassword.Padding = new System.Windows.Forms.Padding(6);
            this.txtPassword.PasswordChar = '*';
            this.txtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword.PlaceholderText = "";
            this.txtPassword.ReadOnly = false;
            this.txtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(478, 69);
            this.txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword.TabIndex = 81;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TextMarginBottom = 0;
            this.txtPassword.TextMarginLeft = 3;
            this.txtPassword.TextMarginTop = 1;
            this.txtPassword.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtPassword, "");
            this.toolTipUsername.SetToolTipIcon(this.txtPassword, null);
            this.toolTipUsername.SetToolTipTitle(this.txtPassword, "");
            this.txtPassword.UseSystemPasswordChar = false;
            this.txtPassword.WordWrap = true;
            // 
            // txtUnitName
            // 
            this.txtUnitName.AcceptsReturn = false;
            this.txtUnitName.AcceptsTab = false;
            this.txtUnitName.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtUnitName.AnimationSpeed = 200;
            this.txtUnitName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUnitName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUnitName.AutoSizeHeight = true;
            this.txtUnitName.BackColor = System.Drawing.Color.Transparent;
            this.txtUnitName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUnitName.BackgroundImage")));
            this.txtUnitName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUnitName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUnitName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUnitName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUnitName.BorderRadius = 20;
            this.txtUnitName.BorderThickness = 1;
            this.txtUnitName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUnitName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUnitName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnitName.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtUnitName.DefaultText = "";
            this.txtUnitName.FillColor = System.Drawing.Color.White;
            this.txtUnitName.HideSelection = true;
            this.txtUnitName.IconLeft = null;
            this.txtUnitName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnitName.IconPadding = 10;
            this.txtUnitName.IconRight = null;
            this.txtUnitName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnitName.Lines = new string[0];
            this.txtUnitName.Location = new System.Drawing.Point(643, 283);
            this.txtUnitName.Margin = new System.Windows.Forms.Padding(6);
            this.txtUnitName.MaxLength = 32767;
            this.txtUnitName.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtUnitName.Modified = false;
            this.txtUnitName.Multiline = false;
            this.txtUnitName.Name = "txtUnitName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnitName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUnitName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnitName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnitName.OnIdleState = stateProperties8;
            this.txtUnitName.Padding = new System.Windows.Forms.Padding(6);
            this.txtUnitName.PasswordChar = '\0';
            this.txtUnitName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUnitName.PlaceholderText = "";
            this.txtUnitName.ReadOnly = false;
            this.txtUnitName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUnitName.SelectedText = "";
            this.txtUnitName.SelectionLength = 0;
            this.txtUnitName.SelectionStart = 0;
            this.txtUnitName.ShortcutsEnabled = true;
            this.txtUnitName.Size = new System.Drawing.Size(480, 69);
            this.txtUnitName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUnitName.TabIndex = 80;
            this.txtUnitName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUnitName.TextMarginBottom = 0;
            this.txtUnitName.TextMarginLeft = 3;
            this.txtUnitName.TextMarginTop = 1;
            this.txtUnitName.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtUnitName, "");
            this.toolTipUsername.SetToolTipIcon(this.txtUnitName, null);
            this.toolTipUsername.SetToolTipTitle(this.txtUnitName, "");
            this.txtUnitName.UseSystemPasswordChar = false;
            this.txtUnitName.WordWrap = true;
            // 
            // lbAvatar
            // 
            this.lbAvatar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.lbAvatar.BackColor = System.Drawing.Color.Transparent;
            this.lbAvatar.Font = new System.Drawing.Font("Arial", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbAvatar.Location = new System.Drawing.Point(73, 217);
            this.lbAvatar.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lbAvatar.Name = "lbAvatar";
            this.lbAvatar.Size = new System.Drawing.Size(156, 27);
            this.lbAvatar.TabIndex = 4;
            this.lbAvatar.TabStop = true;
            this.lbAvatar.Text = "Choose avatar";
            this.toolTipUsername.SetToolTip(this.lbAvatar, "");
            this.toolTipUsername.SetToolTipIcon(this.lbAvatar, null);
            this.toolTipUsername.SetToolTipTitle(this.lbAvatar, "");
            this.lbAvatar.Click += new System.EventHandler(this.lbAvatar_Click);
            // 
            // bunifuLabel19
            // 
            this.bunifuLabel19.AllowParentOverrides = false;
            this.bunifuLabel19.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel19.AutoEllipsis = false;
            this.bunifuLabel19.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel19.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel19.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel19.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel19.Location = new System.Drawing.Point(67, 451);
            this.bunifuLabel19.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel19.Name = "bunifuLabel19";
            this.bunifuLabel19.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel19.Size = new System.Drawing.Size(149, 43);
            this.bunifuLabel19.TabIndex = 92;
            this.bunifuLabel19.Text = "Address:";
            this.bunifuLabel19.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel19.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel19, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel19, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel19, "");
            // 
            // toggleShowPassword
            // 
            this.toggleShowPassword.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.toggleShowPassword.BackColor = System.Drawing.Color.Transparent;
            this.toggleShowPassword.Checked = false;
            this.toggleShowPassword.CheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(5)))), ((int)(((byte)(5)))));
            this.toggleShowPassword.CheckedSwitchColor = System.Drawing.Color.White;
            this.toggleShowPassword.CheckedSwitchStyle = Bunifu.UI.WinForms.BunifuToggleSwitch2.SwitchStyles.Fill;
            this.toggleShowPassword.Location = new System.Drawing.Point(1132, 212);
            this.toggleShowPassword.Name = "toggleShowPassword";
            this.toggleShowPassword.OutlineThickness = 2;
            this.toggleShowPassword.Size = new System.Drawing.Size(99, 59);
            this.toggleShowPassword.TabIndex = 96;
            this.toolTipUsername.SetToolTip(this.toggleShowPassword, "");
            this.toolTipUsername.SetToolTipIcon(this.toggleShowPassword, null);
            this.toolTipUsername.SetToolTipTitle(this.toggleShowPassword, "");
            this.toggleShowPassword.UncheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(189)))), ((int)(((byte)(189)))));
            this.toggleShowPassword.UncheckedSwitchColor = System.Drawing.Color.White;
            this.toggleShowPassword.UncheckedSwitchStyle = Bunifu.UI.WinForms.BunifuToggleSwitch2.SwitchStyles.Fill;
            this.toggleShowPassword.Click += new System.EventHandler(this.toggleShowPassword_CheckedChanged);
            // 
            // txtContactName
            // 
            this.txtContactName.AcceptsReturn = false;
            this.txtContactName.AcceptsTab = false;
            this.txtContactName.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtContactName.AnimationSpeed = 200;
            this.txtContactName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtContactName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtContactName.AutoSizeHeight = true;
            this.txtContactName.BackColor = System.Drawing.Color.Transparent;
            this.txtContactName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtContactName.BackgroundImage")));
            this.txtContactName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtContactName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtContactName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtContactName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtContactName.BorderRadius = 20;
            this.txtContactName.BorderThickness = 1;
            this.txtContactName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtContactName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtContactName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactName.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtContactName.DefaultText = "";
            this.txtContactName.FillColor = System.Drawing.Color.White;
            this.txtContactName.HideSelection = true;
            this.txtContactName.IconLeft = null;
            this.txtContactName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactName.IconPadding = 10;
            this.txtContactName.IconRight = null;
            this.txtContactName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactName.Lines = new string[0];
            this.txtContactName.Location = new System.Drawing.Point(643, 535);
            this.txtContactName.Margin = new System.Windows.Forms.Padding(6);
            this.txtContactName.MaxLength = 32767;
            this.txtContactName.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtContactName.Modified = false;
            this.txtContactName.Multiline = false;
            this.txtContactName.Name = "txtContactName";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtContactName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactName.OnIdleState = stateProperties12;
            this.txtContactName.Padding = new System.Windows.Forms.Padding(6);
            this.txtContactName.PasswordChar = '\0';
            this.txtContactName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtContactName.PlaceholderText = "";
            this.txtContactName.ReadOnly = false;
            this.txtContactName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtContactName.SelectedText = "";
            this.txtContactName.SelectionLength = 0;
            this.txtContactName.SelectionStart = 0;
            this.txtContactName.ShortcutsEnabled = true;
            this.txtContactName.Size = new System.Drawing.Size(480, 69);
            this.txtContactName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtContactName.TabIndex = 94;
            this.txtContactName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtContactName.TextMarginBottom = 0;
            this.txtContactName.TextMarginLeft = 3;
            this.txtContactName.TextMarginTop = 1;
            this.txtContactName.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtContactName, "");
            this.toolTipUsername.SetToolTipIcon(this.txtContactName, null);
            this.toolTipUsername.SetToolTipTitle(this.txtContactName, "");
            this.txtContactName.UseSystemPasswordChar = false;
            this.txtContactName.WordWrap = true;
            // 
            // txtAddress
            // 
            this.txtAddress.AcceptsReturn = false;
            this.txtAddress.AcceptsTab = false;
            this.txtAddress.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtAddress.AnimationSpeed = 200;
            this.txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddress.AutoSizeHeight = true;
            this.txtAddress.BackColor = System.Drawing.Color.Transparent;
            this.txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddress.BackgroundImage")));
            this.txtAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddress.BorderRadius = 20;
            this.txtAddress.BorderThickness = 1;
            this.txtAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtAddress.DefaultText = "";
            this.txtAddress.FillColor = System.Drawing.Color.White;
            this.txtAddress.HideSelection = true;
            this.txtAddress.IconLeft = null;
            this.txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.IconPadding = 10;
            this.txtAddress.IconRight = null;
            this.txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.Lines = new string[0];
            this.txtAddress.Location = new System.Drawing.Point(643, 451);
            this.txtAddress.Margin = new System.Windows.Forms.Padding(6);
            this.txtAddress.MaxLength = 32767;
            this.txtAddress.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtAddress.Modified = false;
            this.txtAddress.Multiline = false;
            this.txtAddress.Name = "txtAddress";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddress.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnIdleState = stateProperties16;
            this.txtAddress.Padding = new System.Windows.Forms.Padding(6);
            this.txtAddress.PasswordChar = '\0';
            this.txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.PlaceholderText = "";
            this.txtAddress.ReadOnly = false;
            this.txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddress.SelectedText = "";
            this.txtAddress.SelectionLength = 0;
            this.txtAddress.SelectionStart = 0;
            this.txtAddress.ShortcutsEnabled = true;
            this.txtAddress.Size = new System.Drawing.Size(480, 69);
            this.txtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddress.TabIndex = 93;
            this.txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddress.TextMarginBottom = 0;
            this.txtAddress.TextMarginLeft = 3;
            this.txtAddress.TextMarginTop = 1;
            this.txtAddress.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtAddress, "");
            this.toolTipUsername.SetToolTipIcon(this.txtAddress, null);
            this.toolTipUsername.SetToolTipTitle(this.txtAddress, "");
            this.txtAddress.UseSystemPasswordChar = false;
            this.txtAddress.WordWrap = true;
            // 
            // txtUnitId
            // 
            this.txtUnitId.AcceptsReturn = false;
            this.txtUnitId.AcceptsTab = false;
            this.txtUnitId.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtUnitId.AnimationSpeed = 200;
            this.txtUnitId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUnitId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUnitId.AutoSizeHeight = true;
            this.txtUnitId.BackColor = System.Drawing.Color.Transparent;
            this.txtUnitId.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUnitId.BackgroundImage")));
            this.txtUnitId.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUnitId.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUnitId.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUnitId.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUnitId.BorderRadius = 20;
            this.txtUnitId.BorderThickness = 1;
            this.txtUnitId.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUnitId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUnitId.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnitId.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtUnitId.DefaultText = "";
            this.txtUnitId.FillColor = System.Drawing.Color.White;
            this.txtUnitId.HideSelection = true;
            this.txtUnitId.IconLeft = null;
            this.txtUnitId.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnitId.IconPadding = 10;
            this.txtUnitId.IconRight = null;
            this.txtUnitId.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUnitId.Lines = new string[0];
            this.txtUnitId.Location = new System.Drawing.Point(643, 367);
            this.txtUnitId.Margin = new System.Windows.Forms.Padding(6);
            this.txtUnitId.MaxLength = 32767;
            this.txtUnitId.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtUnitId.Modified = false;
            this.txtUnitId.Multiline = false;
            this.txtUnitId.Name = "txtUnitId";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnitId.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUnitId.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnitId.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUnitId.OnIdleState = stateProperties20;
            this.txtUnitId.Padding = new System.Windows.Forms.Padding(6);
            this.txtUnitId.PasswordChar = '\0';
            this.txtUnitId.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUnitId.PlaceholderText = "";
            this.txtUnitId.ReadOnly = true;
            this.txtUnitId.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUnitId.SelectedText = "";
            this.txtUnitId.SelectionLength = 0;
            this.txtUnitId.SelectionStart = 0;
            this.txtUnitId.ShortcutsEnabled = true;
            this.txtUnitId.Size = new System.Drawing.Size(480, 69);
            this.txtUnitId.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUnitId.TabIndex = 84;
            this.txtUnitId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUnitId.TextMarginBottom = 0;
            this.txtUnitId.TextMarginLeft = 3;
            this.txtUnitId.TextMarginTop = 1;
            this.txtUnitId.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtUnitId, "");
            this.toolTipUsername.SetToolTipIcon(this.txtUnitId, null);
            this.toolTipUsername.SetToolTipTitle(this.txtUnitId, "");
            this.txtUnitId.UseSystemPasswordChar = false;
            this.txtUnitId.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 20;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(645, 703);
            this.txtEmail.Margin = new System.Windows.Forms.Padding(6);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties24;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(6);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(480, 69);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 83;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 1;
            this.txtEmail.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtEmail, "");
            this.toolTipUsername.SetToolTipIcon(this.txtEmail, null);
            this.toolTipUsername.SetToolTipTitle(this.txtEmail, "");
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtPhoneNumber
            // 
            this.txtPhoneNumber.AcceptsReturn = false;
            this.txtPhoneNumber.AcceptsTab = false;
            this.txtPhoneNumber.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtPhoneNumber.AnimationSpeed = 200;
            this.txtPhoneNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhoneNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhoneNumber.AutoSizeHeight = true;
            this.txtPhoneNumber.BackColor = System.Drawing.Color.Transparent;
            this.txtPhoneNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhoneNumber.BackgroundImage")));
            this.txtPhoneNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPhoneNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhoneNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPhoneNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhoneNumber.BorderRadius = 20;
            this.txtPhoneNumber.BorderThickness = 1;
            this.txtPhoneNumber.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPhoneNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhoneNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhoneNumber.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtPhoneNumber.DefaultText = "";
            this.txtPhoneNumber.FillColor = System.Drawing.Color.White;
            this.txtPhoneNumber.HideSelection = true;
            this.txtPhoneNumber.IconLeft = null;
            this.txtPhoneNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhoneNumber.IconPadding = 10;
            this.txtPhoneNumber.IconRight = null;
            this.txtPhoneNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhoneNumber.Lines = new string[0];
            this.txtPhoneNumber.Location = new System.Drawing.Point(643, 619);
            this.txtPhoneNumber.Margin = new System.Windows.Forms.Padding(6);
            this.txtPhoneNumber.MaxLength = 32767;
            this.txtPhoneNumber.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtPhoneNumber.Modified = false;
            this.txtPhoneNumber.Multiline = false;
            this.txtPhoneNumber.Name = "txtPhoneNumber";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhoneNumber.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhoneNumber.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhoneNumber.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhoneNumber.OnIdleState = stateProperties28;
            this.txtPhoneNumber.Padding = new System.Windows.Forms.Padding(6);
            this.txtPhoneNumber.PasswordChar = '\0';
            this.txtPhoneNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhoneNumber.PlaceholderText = "";
            this.txtPhoneNumber.ReadOnly = false;
            this.txtPhoneNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhoneNumber.SelectedText = "";
            this.txtPhoneNumber.SelectionLength = 0;
            this.txtPhoneNumber.SelectionStart = 0;
            this.txtPhoneNumber.ShortcutsEnabled = true;
            this.txtPhoneNumber.Size = new System.Drawing.Size(480, 69);
            this.txtPhoneNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhoneNumber.TabIndex = 82;
            this.txtPhoneNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhoneNumber.TextMarginBottom = 0;
            this.txtPhoneNumber.TextMarginLeft = 3;
            this.txtPhoneNumber.TextMarginTop = 1;
            this.txtPhoneNumber.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtPhoneNumber, "");
            this.toolTipUsername.SetToolTipIcon(this.txtPhoneNumber, null);
            this.toolTipUsername.SetToolTipTitle(this.txtPhoneNumber, "");
            this.txtPhoneNumber.UseSystemPasswordChar = false;
            this.txtPhoneNumber.WordWrap = true;
            // 
            // btUpdate
            // 
            this.btUpdate.AllowAnimations = true;
            this.btUpdate.AllowMouseEffects = true;
            this.btUpdate.AllowToggling = false;
            this.btUpdate.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btUpdate.AnimationSpeed = 200;
            this.btUpdate.AutoGenerateColors = false;
            this.btUpdate.AutoRoundBorders = false;
            this.btUpdate.AutoSizeLeftIcon = true;
            this.btUpdate.AutoSizeRightIcon = true;
            this.btUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btUpdate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(251)))), ((int)(((byte)(250)))));
            this.btUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btUpdate.BackgroundImage")));
            this.btUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btUpdate.ButtonText = "Update";
            this.btUpdate.ButtonTextMarginLeft = 0;
            this.btUpdate.ColorContrastOnClick = 45;
            this.btUpdate.ColorContrastOnHover = 45;
            this.btUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btUpdate.CustomizableEdges = borderEdges1;
            this.btUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btUpdate.Font = new System.Drawing.Font("Arial Rounded MT Bold", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btUpdate.ForeColor = System.Drawing.Color.Black;
            this.btUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btUpdate.IconMarginLeft = 11;
            this.btUpdate.IconPadding = 10;
            this.btUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btUpdate.IconSize = 25;
            this.btUpdate.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(251)))), ((int)(((byte)(250)))));
            this.btUpdate.IdleBorderRadius = 20;
            this.btUpdate.IdleBorderThickness = 1;
            this.btUpdate.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(251)))), ((int)(((byte)(250)))));
            this.btUpdate.IdleIconLeftImage = null;
            this.btUpdate.IdleIconRightImage = null;
            this.btUpdate.IndicateFocus = false;
            this.btUpdate.Location = new System.Drawing.Point(906, 1152);
            this.btUpdate.Margin = new System.Windows.Forms.Padding(4);
            this.btUpdate.Name = "btUpdate";
            this.btUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btUpdate.OnDisabledState.BorderRadius = 20;
            this.btUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btUpdate.OnDisabledState.BorderThickness = 1;
            this.btUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btUpdate.OnDisabledState.IconLeftImage = null;
            this.btUpdate.OnDisabledState.IconRightImage = null;
            this.btUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btUpdate.onHoverState.BorderRadius = 20;
            this.btUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btUpdate.onHoverState.BorderThickness = 1;
            this.btUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btUpdate.onHoverState.IconLeftImage = null;
            this.btUpdate.onHoverState.IconRightImage = null;
            this.btUpdate.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(251)))), ((int)(((byte)(250)))));
            this.btUpdate.OnIdleState.BorderRadius = 20;
            this.btUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btUpdate.OnIdleState.BorderThickness = 1;
            this.btUpdate.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(251)))), ((int)(((byte)(250)))));
            this.btUpdate.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btUpdate.OnIdleState.IconLeftImage = null;
            this.btUpdate.OnIdleState.IconRightImage = null;
            this.btUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btUpdate.OnPressedState.BorderRadius = 20;
            this.btUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btUpdate.OnPressedState.BorderThickness = 1;
            this.btUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btUpdate.OnPressedState.IconLeftImage = null;
            this.btUpdate.OnPressedState.IconRightImage = null;
            this.btUpdate.Size = new System.Drawing.Size(305, 81);
            this.btUpdate.TabIndex = 93;
            this.btUpdate.TabStop = false;
            this.btUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btUpdate.TextMarginLeft = 0;
            this.btUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.toolTipUsername.SetToolTip(this.btUpdate, "");
            this.toolTipUsername.SetToolTipIcon(this.btUpdate, null);
            this.toolTipUsername.SetToolTipTitle(this.btUpdate, "");
            this.btUpdate.UseDefaultRadiusAndThickness = true;
            this.btUpdate.Click += new System.EventHandler(this.btUpdate_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 40;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.txtNewPassword);
            this.bunifuPanel1.Controls.Add(this.pbAvatar);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel19);
            this.bunifuPanel1.Controls.Add(this.toggleShowPassword);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel15);
            this.bunifuPanel1.Controls.Add(this.txtContactName);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel16);
            this.bunifuPanel1.Controls.Add(this.txtAddress);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel17);
            this.bunifuPanel1.Controls.Add(this.txtUnitId);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel18);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel14);
            this.bunifuPanel1.Controls.Add(this.txtEmail);
            this.bunifuPanel1.Controls.Add(this.txtPhoneNumber);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel12);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.cbUnitType);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel13);
            this.bunifuPanel1.Controls.Add(this.txtPassword);
            this.bunifuPanel1.Controls.Add(this.txtUnitName);
            this.bunifuPanel1.Controls.Add(this.txtUsername);
            this.bunifuPanel1.Controls.Add(this.lbAvatar);
            this.bunifuPanel1.Location = new System.Drawing.Point(441, 237);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1234, 865);
            this.bunifuPanel1.TabIndex = 95;
            this.toolTipUsername.SetToolTip(this.bunifuPanel1, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuPanel1, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuPanel1, "");
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel2.Location = new System.Drawing.Point(269, 205);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(258, 43);
            this.bunifuLabel2.TabIndex = 98;
            this.bunifuLabel2.Text = "New password:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel2, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel2, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel2, "");
            // 
            // txtNewPassword
            // 
            this.txtNewPassword.AcceptsReturn = false;
            this.txtNewPassword.AcceptsTab = false;
            this.txtNewPassword.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtNewPassword.AnimationSpeed = 200;
            this.txtNewPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNewPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNewPassword.AutoSizeHeight = true;
            this.txtNewPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtNewPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNewPassword.BackgroundImage")));
            this.txtNewPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNewPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNewPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNewPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNewPassword.BorderRadius = 20;
            this.txtNewPassword.BorderThickness = 1;
            this.txtNewPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNewPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNewPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtNewPassword.DefaultText = "";
            this.txtNewPassword.FillColor = System.Drawing.Color.White;
            this.txtNewPassword.HideSelection = true;
            this.txtNewPassword.IconLeft = null;
            this.txtNewPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.IconPadding = 10;
            this.txtNewPassword.IconRight = null;
            this.txtNewPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNewPassword.Lines = new string[0];
            this.txtNewPassword.Location = new System.Drawing.Point(645, 202);
            this.txtNewPassword.Margin = new System.Windows.Forms.Padding(6);
            this.txtNewPassword.MaxLength = 32767;
            this.txtNewPassword.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtNewPassword.Modified = false;
            this.txtNewPassword.Multiline = false;
            this.txtNewPassword.Name = "txtNewPassword";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNewPassword.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNewPassword.OnIdleState = stateProperties32;
            this.txtNewPassword.Padding = new System.Windows.Forms.Padding(6);
            this.txtNewPassword.PasswordChar = '*';
            this.txtNewPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNewPassword.PlaceholderText = "";
            this.txtNewPassword.ReadOnly = false;
            this.txtNewPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNewPassword.SelectedText = "";
            this.txtNewPassword.SelectionLength = 0;
            this.txtNewPassword.SelectionStart = 0;
            this.txtNewPassword.ShortcutsEnabled = true;
            this.txtNewPassword.Size = new System.Drawing.Size(480, 69);
            this.txtNewPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNewPassword.TabIndex = 99;
            this.txtNewPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNewPassword.TextMarginBottom = 0;
            this.txtNewPassword.TextMarginLeft = 3;
            this.txtNewPassword.TextMarginTop = 1;
            this.txtNewPassword.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtNewPassword, "");
            this.toolTipUsername.SetToolTipIcon(this.txtNewPassword, null);
            this.toolTipUsername.SetToolTipTitle(this.txtNewPassword, "");
            this.txtNewPassword.UseSystemPasswordChar = false;
            this.txtNewPassword.WordWrap = true;
            // 
            // pbAvatar
            // 
            this.pbAvatar.AllowFocused = false;
            this.pbAvatar.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.pbAvatar.AutoSizeHeight = true;
            this.pbAvatar.BorderRadius = 80;
            this.pbAvatar.Image = ((System.Drawing.Image)(resources.GetObject("pbAvatar.Image")));
            this.pbAvatar.IsCircle = false;
            this.pbAvatar.Location = new System.Drawing.Point(69, 49);
            this.pbAvatar.Margin = new System.Windows.Forms.Padding(6);
            this.pbAvatar.Name = "pbAvatar";
            this.pbAvatar.Size = new System.Drawing.Size(160, 160);
            this.pbAvatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbAvatar.TabIndex = 97;
            this.pbAvatar.TabStop = false;
            this.toolTipUsername.SetToolTip(this.pbAvatar, "");
            this.toolTipUsername.SetToolTipIcon(this.pbAvatar, null);
            this.toolTipUsername.SetToolTipTitle(this.pbAvatar, "");
            this.pbAvatar.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuLabel15
            // 
            this.bunifuLabel15.AllowParentOverrides = false;
            this.bunifuLabel15.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel15.AutoEllipsis = false;
            this.bunifuLabel15.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel15.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel15.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel15.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel15.Location = new System.Drawing.Point(67, 367);
            this.bunifuLabel15.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel15.Name = "bunifuLabel15";
            this.bunifuLabel15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel15.Size = new System.Drawing.Size(128, 43);
            this.bunifuLabel15.TabIndex = 83;
            this.bunifuLabel15.Text = "Unit ID:";
            this.bunifuLabel15.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel15.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel15, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel15, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel15, "");
            // 
            // bunifuLabel16
            // 
            this.bunifuLabel16.AllowParentOverrides = false;
            this.bunifuLabel16.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel16.AutoEllipsis = false;
            this.bunifuLabel16.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel16.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel16.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel16.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel16.Location = new System.Drawing.Point(67, 283);
            this.bunifuLabel16.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel16.Name = "bunifuLabel16";
            this.bunifuLabel16.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel16.Size = new System.Drawing.Size(185, 43);
            this.bunifuLabel16.TabIndex = 82;
            this.bunifuLabel16.Text = "Unit name:";
            this.bunifuLabel16.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel16.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel16, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel16, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel16, "");
            // 
            // bunifuLabel17
            // 
            this.bunifuLabel17.AllowParentOverrides = false;
            this.bunifuLabel17.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel17.AutoEllipsis = false;
            this.bunifuLabel17.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel17.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel17.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel17.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel17.Location = new System.Drawing.Point(267, 130);
            this.bunifuLabel17.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel17.Name = "bunifuLabel17";
            this.bunifuLabel17.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel17.Size = new System.Drawing.Size(310, 43);
            this.bunifuLabel17.TabIndex = 81;
            this.bunifuLabel17.Text = "Current password:";
            this.bunifuLabel17.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel17.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel17, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel17, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel17, "");
            // 
            // bunifuLabel18
            // 
            this.bunifuLabel18.AllowParentOverrides = false;
            this.bunifuLabel18.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel18.AutoEllipsis = false;
            this.bunifuLabel18.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel18.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel18.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel18.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel18.Location = new System.Drawing.Point(267, 55);
            this.bunifuLabel18.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel18.Name = "bunifuLabel18";
            this.bunifuLabel18.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel18.Size = new System.Drawing.Size(185, 43);
            this.bunifuLabel18.TabIndex = 80;
            this.bunifuLabel18.Text = "Username:";
            this.bunifuLabel18.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel18.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel18, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel18, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel18, "");
            // 
            // bunifuLabel14
            // 
            this.bunifuLabel14.AllowParentOverrides = false;
            this.bunifuLabel14.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel14.AutoEllipsis = false;
            this.bunifuLabel14.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel14.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel14.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel14.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel14.Location = new System.Drawing.Point(67, 535);
            this.bunifuLabel14.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel14.Name = "bunifuLabel14";
            this.bunifuLabel14.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel14.Size = new System.Drawing.Size(248, 43);
            this.bunifuLabel14.TabIndex = 84;
            this.bunifuLabel14.Text = "Contact name:";
            this.bunifuLabel14.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel14.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel14, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel14, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel14, "");
            // 
            // bunifuLabel12
            // 
            this.bunifuLabel12.AllowParentOverrides = false;
            this.bunifuLabel12.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel12.AutoEllipsis = false;
            this.bunifuLabel12.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel12.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel12.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel12.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel12.Location = new System.Drawing.Point(67, 619);
            this.bunifuLabel12.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel12.Name = "bunifuLabel12";
            this.bunifuLabel12.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel12.Size = new System.Drawing.Size(259, 43);
            this.bunifuLabel12.TabIndex = 87;
            this.bunifuLabel12.Text = "Phone number:";
            this.bunifuLabel12.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel12, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel12, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel12, "");
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel1.Location = new System.Drawing.Point(67, 787);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(161, 43);
            this.bunifuLabel1.TabIndex = 71;
            this.bunifuLabel1.Text = "Unit type:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel1, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel1, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // cbUnitType
            // 
            this.cbUnitType.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.cbUnitType.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbUnitType.FormattingEnabled = true;
            this.cbUnitType.Items.AddRange(new object[] {
            "Hospital",
            "Clinic",
            "Nursing home"});
            this.cbUnitType.Location = new System.Drawing.Point(645, 787);
            this.cbUnitType.Margin = new System.Windows.Forms.Padding(6);
            this.cbUnitType.Name = "cbUnitType";
            this.cbUnitType.Size = new System.Drawing.Size(480, 45);
            this.cbUnitType.TabIndex = 72;
            this.toolTipUsername.SetToolTip(this.cbUnitType, "");
            this.toolTipUsername.SetToolTipIcon(this.cbUnitType, null);
            this.toolTipUsername.SetToolTipTitle(this.cbUnitType, "");
            // 
            // bunifuLabel13
            // 
            this.bunifuLabel13.AllowParentOverrides = false;
            this.bunifuLabel13.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel13.AutoEllipsis = false;
            this.bunifuLabel13.BackColor = System.Drawing.Color.AntiqueWhite;
            this.bunifuLabel13.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel13.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel13.Font = new System.Drawing.Font("Arial", 14.25F);
            this.bunifuLabel13.Location = new System.Drawing.Point(67, 703);
            this.bunifuLabel13.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel13.Name = "bunifuLabel13";
            this.bunifuLabel13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel13.Size = new System.Drawing.Size(108, 43);
            this.bunifuLabel13.TabIndex = 86;
            this.bunifuLabel13.Text = "Email:";
            this.bunifuLabel13.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel13, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel13, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel13, "");
            // 
            // txtUsername
            // 
            this.txtUsername.AcceptsReturn = false;
            this.txtUsername.AcceptsTab = false;
            this.txtUsername.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.txtUsername.AnimationSpeed = 200;
            this.txtUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsername.AutoSizeHeight = true;
            this.txtUsername.BackColor = System.Drawing.Color.Transparent;
            this.txtUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsername.BackgroundImage")));
            this.txtUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUsername.BorderRadius = 20;
            this.txtUsername.BorderThickness = 1;
            this.txtUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.DefaultFont = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtUsername.DefaultText = "";
            this.txtUsername.FillColor = System.Drawing.Color.White;
            this.txtUsername.HideSelection = true;
            this.txtUsername.IconLeft = null;
            this.txtUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.IconPadding = 10;
            this.txtUsername.IconRight = null;
            this.txtUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.Lines = new string[0];
            this.txtUsername.Location = new System.Drawing.Point(643, 38);
            this.txtUsername.Margin = new System.Windows.Forms.Padding(6);
            this.txtUsername.MaxLength = 32767;
            this.txtUsername.MinimumSize = new System.Drawing.Size(2, 2);
            this.txtUsername.Modified = false;
            this.txtUsername.Multiline = false;
            this.txtUsername.Name = "txtUsername";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsername.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnIdleState = stateProperties36;
            this.txtUsername.Padding = new System.Windows.Forms.Padding(6);
            this.txtUsername.PasswordChar = '\0';
            this.txtUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUsername.PlaceholderText = "";
            this.txtUsername.ReadOnly = true;
            this.txtUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsername.SelectedText = "";
            this.txtUsername.SelectionLength = 0;
            this.txtUsername.SelectionStart = 0;
            this.txtUsername.ShortcutsEnabled = true;
            this.txtUsername.Size = new System.Drawing.Size(478, 69);
            this.txtUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsername.TabIndex = 79;
            this.txtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsername.TextMarginBottom = 0;
            this.txtUsername.TextMarginLeft = 3;
            this.txtUsername.TextMarginTop = 1;
            this.txtUsername.TextPlaceholder = "";
            this.toolTipUsername.SetToolTip(this.txtUsername, "");
            this.toolTipUsername.SetToolTipIcon(this.txtUsername, null);
            this.toolTipUsername.SetToolTipTitle(this.txtUsername, "");
            this.txtUsername.UseSystemPasswordChar = false;
            this.txtUsername.WordWrap = true;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel11.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel11.Font = new System.Drawing.Font("Arial Rounded MT Bold", 21.75F);
            this.bunifuLabel11.Location = new System.Drawing.Point(841, 136);
            this.bunifuLabel11.Margin = new System.Windows.Forms.Padding(6);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(434, 67);
            this.bunifuLabel11.TabIndex = 92;
            this.bunifuLabel11.Text = "Unit Informaion";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.toolTipUsername.SetToolTip(this.bunifuLabel11, "");
            this.toolTipUsername.SetToolTipIcon(this.bunifuLabel11, null);
            this.toolTipUsername.SetToolTipTitle(this.bunifuLabel11, "");
            // 
            // toolTipUsername
            // 
            this.toolTipUsername.Active = true;
            this.toolTipUsername.AlignTextWithTitle = false;
            this.toolTipUsername.AllowAutoClose = false;
            this.toolTipUsername.AllowFading = true;
            this.toolTipUsername.AutoCloseDuration = 5000;
            this.toolTipUsername.BackColor = System.Drawing.SystemColors.Control;
            this.toolTipUsername.BorderColor = System.Drawing.Color.Gainsboro;
            this.toolTipUsername.ClickToShowDisplayControl = false;
            this.toolTipUsername.ConvertNewlinesToBreakTags = true;
            this.toolTipUsername.DisplayControl = null;
            this.toolTipUsername.EntryAnimationSpeed = 350;
            this.toolTipUsername.ExitAnimationSpeed = 200;
            this.toolTipUsername.GenerateAutoCloseDuration = false;
            this.toolTipUsername.IconMargin = 6;
            this.toolTipUsername.InitialDelay = 0;
            this.toolTipUsername.Name = "toolTipUsername";
            this.toolTipUsername.Opacity = 1D;
            this.toolTipUsername.OverrideToolTipTitles = false;
            this.toolTipUsername.Padding = new System.Windows.Forms.Padding(10);
            this.toolTipUsername.ReshowDelay = 100;
            this.toolTipUsername.ShowAlways = true;
            this.toolTipUsername.ShowBorders = false;
            this.toolTipUsername.ShowIcons = true;
            this.toolTipUsername.ShowShadows = true;
            this.toolTipUsername.Tag = null;
            this.toolTipUsername.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.toolTipUsername.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.toolTipUsername.TextMargin = 2;
            this.toolTipUsername.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.toolTipUsername.TitleForeColor = System.Drawing.Color.Black;
            this.toolTipUsername.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.toolTipUsername.ToolTipTitle = null;
            // 
            // UC_UnitInformation
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 25F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.btUpdate);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.bunifuLabel11);
            this.DoubleBuffered = true;
            this.Margin = new System.Windows.Forms.Padding(6);
            this.Name = "UC_UnitInformation";
            this.Size = new System.Drawing.Size(2116, 1500);
            this.toolTipUsername.SetToolTip(this, "");
            this.toolTipUsername.SetToolTipIcon(this, null);
            this.toolTipUsername.SetToolTipTitle(this, "");
            this.Load += new System.EventHandler(this.UC_UnitInformation_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtUnitName;
        private System.Windows.Forms.LinkLabel lbAvatar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel19;
        private Bunifu.UI.WinForms.BunifuToggleSwitch2 toggleShowPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtContactName;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddress;
        private Bunifu.UI.WinForms.BunifuTextBox txtUnitId;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuTextBox txtPhoneNumber;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btUpdate;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel15;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel16;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel17;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel18;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel14;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.ComboBox cbUnitType;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuTextBox txtUsername;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuPictureBox pbAvatar;
        private Bunifu.UI.WinForms.BunifuToolTip toolTipUsername;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtNewPassword;
    }
}
